### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by doantranthanh** [Xuyuanp/nerdtree-git-plugin#105]
hi all,

I am using Conemu with VIM on Windows 10. However, Icons are not showing with the plugin. 

I tried many way but no luck. Here is my image of vim

![image](https://user-images.githubusercontent.com/9557564/44594407-01c34780-a7be-11e8-81f1-43f275747730.png)

and here is my vimrc which has many other plugin.
[vimrc.txt](https://github.com/Xuyuanp/nerdtree-git-plugin/files/2319041/vimrc.txt)

Please could you help me?

Thanks

**Comment by minusmario** [comment]
same issue here, got some errors while change shell to powershell:
Error detected while processing function <SNR>35_CursorHoldUpdate[18]..161[1]..39[1]..264[4]..NERDTreeGitStatusRefreshListener[5]..NERDTreeGetGitStatusPrefix[3]..NERDTreeGitStatusRefresh:
line   16:
E484: Can't open file C:/Users/zhangtz/AppData/Local/Temp/VIoC2DD.tmp
4 fewer lines
1: 
...
Error detected while processing function 203[2]..204[12]..187[20]..190[8]..154[25]..152[15]..264[4]..NERDTreeGitStatusRefreshListener[2]..NERDTreeGitStatusRefresh:
line   16:
E484: Can't open file C:/.../.../AppData/Local/Temp/VIoCBED.tmp
Error detected while processing function 203[2]..204[12]..187[20]..190[8]..154:
line   25:
E171: Missing :endif
Error detected while processing function 203[2]..204:
line   12:
E171: Missing :endif
E488: Trailing characters
E488: Trailing characters

Using VIM 8.1 under windows 7 together with Vundle

**Comment by jaypikay** [comment]
Have you tried to disable the "vim-devicons" plugin?

**Comment by Xuyuanp** [comment]
Sorry, too late
Does it work now?

**Comment by killermag** [comment]
@Xuyuanp Nope, for me too it doesnt work.

**Comment by Xuyuanp** [comment]
vimrc please

**Comment by Xuyuanp** [comment]
@doantranthanh I can not reproduce with your vimrc on my mac.

**Comment by YvesZHI** [comment]
@Xuyuanp    Have you tried this plugin with Vim 8.2? I'm using Vim 8.2 and I have the same issue.

**Comment by Xuyuanp** [comment]
@YvesZHI, please open a new issue.
