### ISSUE TITLE
Not working at all under Windows 10

### ISSUE THREAD

**Issue by jadero** [Xuyuanp/nerdtree-git-plugin#106]
Did some debugging and found out that applying the following fix makes it working:
`let l:root = fnamemodify(b:NERDTree.root.path.str(), ':p:gs?\\?/?:S')`.
The modifier `:gs?\\?/?` replaces all backward slashes with forward slashes.
Not sure about any side effects though.

**Comment by bbblitz** [comment]
Broken for me too, the above fix works for me too.
For anyone stumbling across this trying to fix their nerdtree-git-plugin, modify line 81 in git_status.vim to what @jadero posted.
