### ISSUE TITLE
untracked flag doesn't showup.

### ISSUE THREAD

**Issue by cevhyruz** [Xuyuanp/nerdtree-git-plugin#109]
Whenever I create a new directory and add some files on it, the `untracked` flag doesn't show up, It just shows the `dirty` flag on the newly created directory but no `untracked` flag for the files inside.

Is this a limitation or a bug?
I use this modified snippet from the README:
```
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "M",
    \ "Staged"    : "✚",
    \ "Untracked" : "?",
    \ "Renamed"   : "R",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "D",
    \ "Dirty"     : "!",
    \ "Clean"     : "✔︎",
    \ 'Ignored'   : 'i',
    \ "Unknown"   : "u"
    \ }

let g:NERDTreeShowIgnoredStatus = 1
```

**Comment by Xuyuanp** [comment]
It's feature. `git status` outputs new dir in a single line
