### ISSUE TITLE
Bug with function! s:FileUpdate(fname) function

### ISSUE THREAD

**Issue by dmix75** [Xuyuanp/nerdtree-git-plugin#110]
Consider that function may need to be rewritten.  The if statement that contains a return may run and calling buffer will never be reset by the end of the function and you won't go back to the original.  You may end up with the path of the NERD_TREE_1 tab

function! s:FileUpdate(fname)
    if g:NERDTreeUpdateOnWrite != 1
        return
    endif

    if !g:NERDTree.IsOpen()
        return
    endif

    let l:winnr = winnr()
    let l:altwinnr = winnr('#')

    call g:NERDTree.CursorToTreeWin()
    let l:node = b:NERDTree.root.findNode(g:NERDTreePath.New(a:fname))
    if l:node != {}
        call l:node.refreshFlags()
        let l:node = l:node.parent
        while !empty(l:node)
            call l:node.refreshDirFlags()
            let l:node = l:node.parent
        endwhile
        call NERDTreeRender()
    endif

    exec l:altwinnr . 'wincmd w'
    exec l:winnr . 'wincmd w'
endfunction

**Comment by Xuyuanp** [comment]
Thanks, fixed
