### ISSUE TITLE
Hiding/Removing Square Brackets: [ ]

### ISSUE THREAD

**Issue by oguzbilgic** [Xuyuanp/nerdtree-git-plugin#114]
Hi there, Since we are already using distinct unicode symbols for each status, I was wondering if there is a way to hide the square brackets `[` `]` around the status symbols.

<img width="93" alt="screen shot 2019-01-15 at 12 35 35 am" src="https://user-images.githubusercontent.com/144778/51168309-b9d0ba00-185d-11e9-9a22-ac3510d4a439.png">

I tried `:set conceallevel=3` per this answer https://github.com/Xuyuanp/nerdtree-git-plugin/issues/88#issuecomment-371706501 however It doesn't seem to have any effect.

**Comment by pirey** [comment]
i was also looking for a solution for this,

unfortunately this is not related to this plugin,
the square brackets is [hard-coded](https://github.com/scrooloose/nerdtree/blob/master/lib/nerdtree/flag_set.vim#L55) in the main nerdtree plugin, and i guess they don't provide any option to disable/hide it.

**Comment by Xuyuanp** [comment]
maybe you will like [ryanoasis/vim-devicons](https://github.com/ryanoasis/vim-devicons)
