### ISSUE TITLE
Add option to show folders as modified instead of dirty

### ISSUE THREAD

**Issue by nkakouros** [Xuyuanp/nerdtree-git-plugin#115]
I do not know if the correct terminology is indeed that folders containing modified files are 'dirty'. However, it is counter-intuitive for me. When I stage the whole folder (`git add dirty-folder`), then the folder is still displayed as 'dirty' by `nerdtree-git-plugin`, when it would be clearer if it showed as 'staged'.

**Comment by Xuyuanp** [comment]
Implemented. Please update and add this line in your `vimrc`
```vim
let g:NERDTreeGitStatusDirDirtyOnly = 0
```
