### ISSUE TITLE
Refresh in Insert Mode

### ISSUE THREAD

**Issue by tombh** [Xuyuanp/nerdtree-git-plugin#123]
Does anyone know of a way to call the refresh function from my vimrc? Eg;

`autocmd CursorHoldI * call s:CursorHoldUpdate()`

But of course that doesn't work because the function is scoped to the script with `s:`.

**Comment by yzzy** [comment]
There is some hacky way to do this:
https://vi.stackexchange.com/questions/17866/are-script-local-functions-sfuncname-unit-testable

But why don't you simply add `CursorHoldI` event to the existing `autocmd` plugin line?
`autocmd CursorHold,CursorHoldI * silent! call s:CursorHoldUpdate()`

**Comment by tombh** [comment]
Oh interesting! I'll have a play with those SO suggestions, thank you.

But this would `autocmd CursorHold,CursorHoldI * silent! call s:CursorHoldUpdate()` lives in the plugin code right? And then I would have to maintain my own fork?

**Comment by yzzy** [comment]
Yes, you should edit plugin code.
You don't need your own fork if this is the only change you've made, you can edit plugin source right on local filesystem.

**Comment by tombh** [comment]
I see yes. That's reasonable, the plugin doesn't change much so there's not much danger of updates generating merge conflicts.
