### ISSUE TITLE
PLEASE replace the default icon with NerdFont

### ISSUE THREAD

**Issue by yuanzhel** [Xuyuanp/nerdtree-git-plugin#124]
See with the nerd font mono fix font, your plugin will work cross all platform.
Whether i'm using my host machine, or i'm ssh to it, there will be no mess text showing.
But now since your icon is not mono space, there is some mess space showing when ssh,
which it's hard to fix and really disturb me.

Thanks for giving this awesome plugin, hope you can update to make it more cool.

**Comment by Xuyuanp** [comment]
sorry for too late.

you can set custom flag by `g:NERDTreeIndicatorMapCustom` var
