### ISSUE TITLE
nerdtree-git-plugin conflicts with python-mode

### ISSUE THREAD

**Issue by jpch89** [Xuyuanp/nerdtree-git-plugin#125]
When I have nerdtree-git-plugin and python-mode both installed, and try to use :PymodeLintAuto and :PymodeLint command, this error message keeps poping up:

"adminforms.py" 6L, 205C 已写入
处理 function pymode#buffer_post_write 时发生错误:
第    8 行:
E121: 未定义的变量: b:pymode_modified
E15: 无效的表达式: g:pymode_lint_unmodified || (g:pymode_lint_on_write && b:pymode_modified)

An Issue has already been submitted on python-mode project and yet not closed. I'm not sure which plugin should be modified in order to solve the problem. Maybe someone here knows the answer.

Related Link:
https://github.com/python-mode/python-mode/issues/1006

**Comment by jpch89** [comment]
I have to correct my statement.
The error messages appear to have something to do with `:w<cr>` command, not `:PymodeLintAuto` nor `:PymodeLint`.

**Comment by nineKnight** [comment]
Add this into your .vimrc and it may help:
```
let NERDTreeIgnore=['\.pyc', '\~$']
```

**Comment by jpch89** [comment]
It's werid that I can't reproduce the error now.
Maybe it's because I wrote this line in my vimrc:
`let NERDTreeIgnore = ['^__pycache__$']`
Anyway, I'm going to add `'\.pyc'` and '\~$' to the list as well.
Thank you very much for your help @nineKnight .
