### ISSUE TITLE
Wrong background color on directories

### ISSUE THREAD

**Issue by hbarcelos** [Xuyuanp/nerdtree-git-plugin#127]
Installed plugins:

Theme: nord

```vim
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
```

Relevant config:

```vim
let g:NERDTreeShowIgnoredStatus = 1
```

Screenshot:

![image](https://user-images.githubusercontent.com/16565602/63062589-e3bf8d00-becf-11e9-855a-2ee413d40b9e.png)

How can I clear this highlighting?

**Comment by Xuyuanp** [comment]
This is the default `Ignored` indicator, you can set `g:NERDTreeIndicatorMapCustom` by yourself. Please see readme

**Comment by hbarcelos** [comment]
Sorry, I don't think I made myself clear enough: it's NOT the icon that bothers me, it's the nasty background color, which I can't get rid of, no matter what theme I use.

**Comment by Xuyuanp** [comment]
Please see here https://github.com/preservim/nerdtree/pull/1157
