### ISSUE TITLE
Breaks if you open a directory with `vim .`

### ISSUE THREAD

**Issue by blokezero** [Xuyuanp/nerdtree-git-plugin#13]
Steps to reproduce, 
1. install nerdtree and nredtree-git
2. cd to project directory
3. type `vim .`

1st Nerdtree window (where you would expect to see the directory listing as usual) is empty.  It appears in the main window though (as usual without nerdtree-git)

Output:
    "." is a directory
    Error detected while processing function      176..177..180..143..141..223..NERDTreeGitStatusRefreshListener..NERDTreeGetGitStatusPrefix:
    line   16:
    E121: Undefined variable: b:NERDTreeCachedGitFileStatus

**Comment by Xuyuanp** [comment]
It works well here as your description. More details please?

**Comment by blokezero** [comment]
Ok, it's OSX 10.10.2.  Shell is zsh

Vim installed via homebrew:

    From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/vim.rb
    ==> Dependencies
    Optional: lua ✘, luajit ✘
    ==> Options
    --disable-nls
    	Build vim without National Language Support (translated messages, keymaps)
    --override-system-vi
    	Override system vi
    --with-client-server
    	Enable client/server mode
    --with-lua
    	Build vim with lua support
    --with-luajit
    	Build with luajit support
    --with-mzscheme
    	Build vim with mzscheme support
    --with-python3
    	Build vim with python3 instead of python[2] support
    --with-tcl
    	Build vim with tcl support
    --without-perl
    	Build vim without perl support
    --without-python
    	Build vim without python support
    --without-ruby
    	Build vim without ruby support
    --HEAD
    	Install HEAD version

Plugins installed using [pathogen](https://github.com/tpope/vim-pathogen)

Relevant pieces of my .vimrc

    "Autostart NERDTree on VIM start
    autocmd VimEnter * NERDTree
    let NERDTreeShowHidden=1
    
    " ----- jistr/vim-nerdtree-tabs -----
    " Open/close NERDTree Tabs with \t
    nmap <silent> <leader>t :NERDTreeTabsToggle<CR>
    " To have NERDTree always open on startup
    let g:nerdtree_tabs_open_on_console_startup = 0

Let me know if I can do or supply anything else.

Great plug in!

![screenshot 2015-03-04 09 48 31](https://cloud.githubusercontent.com/assets/214196/6481236/abd1852e-c253-11e4-8b99-2a2471a7fca7.png)
![screenshot 2015-03-04 09 29 32](https://cloud.githubusercontent.com/assets/214196/6481237/abf5dffa-c253-11e4-9a1b-ed8f88fd21b8.png)

**Comment by Xuyuanp** [comment]
OK, got it! 

This problem is caused by this line `autocmd VimEnter * NERDTree`. 

Command `vim <dir>` starts vim and opens nerdtree window automatically, so there would be two nerdtree windows if you set this line even if without my plugin. 

So this bug (if it was) belongs to nerdtree.

Just remove `autocmd VimEnter * NERDTree`.

**Comment by blokezero** [comment]
Hi,
I have that line there so that when I open a directory it automatically opens in a 'Project view' with all the files on the left, that is not the problem.

This is the problem:  When I type `vim .` I expect to see all the files in BOTH NERDTree views, but because of the errors listed the left window is empty and has no tree in it.

And the following errors do not appear if I uninstall your plugin:

Error detected while processing function 176..177..180..143..141..223..NERDTreeGitStatusRefreshListener..NERDTreeGetGitStatusPrefix:
line   16:
E121: Undefined variable: b:NERDTreeCachedGitFileStatus

Error detected while processing function 176..177..180..143..141..223..NERDTreeGitStatusRefreshListener..NERDTreeGetGitStatusPrefix:
line   16:
E116: Invalid arguments for function get(b:NERDTreeCachedGitFileStatus, fnameescape(pathStr), "")

Error detected while processing function 176..177..180..143..141..223..NERDTreeGitStatusRefreshListener..NERDTreeGetGitStatusPrefix:
line   16:
E15: Invalid expression: get(b:NERDTreeCachedGitFileStatus, fnameescape(pathStr), "")

Error detected while processing function 176..177..180..143:
line    9:
E171: Missing :endif

Hope thats helpful.

**Comment by jamesthomasonjr** [comment]
@blokezero I was having similar problems.
I was switching from pathogen to NeoBundle when I ran into the bug, and have temporarily fixed it by using an older version of the plugin:
```NeoBundle 'Xuyuanp/nerdtree-git-plugin', { 'rev' : '4d44de' }```

Installing revision 81b70d or newer breaks the plugin, so the bug most likely has something to do with the switch from global/script level variables to buffer level variables.

**Comment by blokezero** [comment]
@jamesthomasonjr that works for me too, I'm pretty committed to using pathogen so I just checked out that commit and it temporarily fixes the problem for me.  Thanks for the heads up.

**Comment by LmtEdition** [comment]
I'm getting the same problem. I'm running vim 7.3 on OSX Yosemite, fish shell. 

I don't understand why, but s:GitStatusCacheTime is the current local time before g:NERDTreeGitStatusRefresh is ever called. So the initial check in g:NERDTreeGetGitStatusPrefix function always fails (localtime() - s:GitStatusCacheTime > s:GitStatusCacheTimeExpiry), g:NERDTreeGitStatusRefresh is never called, and I guess that's why I'm seeing the error message: 

E121: Undefined variable: b:NERDTreeCachedGitFileStatus

One easy fix that works for me is removing the CacheTime checks completely. However, I see a 1 sec delay when opening directories from outside vim when using this plugin, compared to when I turn this plugin off.

**Comment by bcgraham** [comment]
i got this error today. similar to @LmtEdition, using OSX & fish shell. i've had problems in the past with vim plugins and fish. i fixed it by adding the below to my `.vimrc`:
```vim
set shell=/bin/bash
```

**Comment by jamsyoung** [comment]
To add more context to when this error occurs - I get this error when typing `vim .` in sub-directories that are stored on Dropbox.
