### ISSUE TITLE
Any relation to this Plugin 'Xuyuanp/nerdtree-gitplugin'?

### ISSUE THREAD

**Issue by sweetim** [Xuyuanp/nerdtree-git-plugin#135]
I accidentally type to use the plugin below, and it ask for my github authentication when I run `vim +PluginInstall +qall` to install the plugins using `vundle` , is there any relationship between the plugin below and this? is it normal to ask for github authentication?

```
Plugin 'Xuyuanp/nerdtree-gitplugin'
```

since both package has the same author, i submit an issue in this repo

**Comment by wowpoppy** [comment]
Happens if you're trying to access nonexistent or private repository. Git asks to authenticate to check which is the case to clone the repository if it really exists and is private
