### ISSUE TITLE
very slow with nerdtree side panel

### ISSUE THREAD

**Issue by pinggit** [Xuyuanp/nerdtree-git-plugin#136]
with nerdtree side panel opened, moving in file is VERY slow.
good after close side panel, good after disable the plugin, so looks like a bug.
I see a few similar issues reported earlier, but I don't see any solution.
is this by design, or are there any known workaround?
thanks!

**Comment by wedgwood** [comment]
+1

**Comment by Xuyuanp** [comment]
I have to say sorry that it does can be very slow if you open a large directory. You can try to set `g:NERDTreeGitStatusUpdateOnWrite` and `g:NERDTreeGitStatusUpdateOnCursorHold` to `0` to disable live update.
