### ISSUE TITLE
Anyway to disable git scan on hidden buffer?

### ISSUE THREAD

**Issue by bgreenacre** [Xuyuanp/nerdtree-git-plugin#138]
So when I split open a file from nerdtree and then nav my buffers to show one buffer completely and hide all others it seems upon the nerdtree refresh this git plugin causes any hidden buffer to show the first line within the file. Is there anyway to avoid this? I've attached a screencap of what I'm talking about. I hope it helps demonstrate my issue.

Notice the first line of the hidden buffer shows up at the top of the terminal window...

![demo](https://user-images.githubusercontent.com/167656/85348384-14ddf600-b4c1-11ea-95ab-7329be8cb602.gif)

**Comment by Xuyuanp** [comment]
Hi, how do you hide other buffers?
