### ISSUE TITLE
Highlight changes after resource $VIMRC

### ISSUE THREAD

**Issue by soulomoon** [Xuyuanp/nerdtree-git-plugin#139]
Highlight changes after resource $VIMRC
* brefor resourcing
<img width="109" alt="Screen Shot 2020-06-26 at 01 50 38" src="https://user-images.githubusercontent.com/14073857/85772600-95198b00-b74f-11ea-97ad-dfeaeb0cff4e.png">
* after resourcing
<img width="116" alt="Screen Shot 2020-06-26 at 01 50 17" src="https://user-images.githubusercontent.com/14073857/85772700-aebad280-b74f-11ea-80bc-00760c16b777.png">

**Comment by Xuyuanp** [comment]
This plugin set syntax highlighting only when and only when loaded at the first time
