### ISSUE TITLE
Not working for subdirectories

### ISSUE THREAD

**Issue by delijati** [Xuyuanp/nerdtree-git-plugin#14]
I thinks thats more an feature request than a bug. Git status it is only run in the root directory, but in my projects i have multiple repos in subdirectories and changes there are therefor not highlighted.

**Comment by Xuyuanp** [comment]
I had tried to implemented ever. But I gave it up finally. Because it's impossible to find out all the subdirectories which was holding a repo without traveling all subdir and checking one by one.
It will be very very very slow if there were lots of subdir and dir tree was very deep.

**Comment by delijati** [comment]
Maybe there is is a event in nerdtree when a folder is open and we coul trigger that the git status check on it.

**Comment by Xuyuanp** [comment]
Changing nerdtree code is needed in this way.

**Comment by numbnut** [comment]
Would it be a solution to introduce a property which defines the maximum deepness to scan for git repos, which defaults to 1. I think that it's a common case to open a folder with git projects.

**Comment by PhilRunninger** [comment]
@delijati, when you say "subdirectories" are you referring to git submodules? If so then, @Xuyuanp, there is an alternative to searching the entire tree. In the repo's root folder is a file named `.gitmodules`, which lists all the submodules included in the repo.

**Comment by shiluotang** [comment]
It's not working in subdirectories even if the parent contains a ".git". THIS IS NOT THE SUBMODULE situation.

**Comment by slabua** [comment]
I found myself in a similar situation, perhaps.
I had my terminal in a generic path, then with nerdtree I navigated the file system to the root of a repository which contained some changes and I was expecting to see the icons accordingly.
I then tried again, I thought I had misconfigured the plugin, somehow. This time by placing myself in the root of the repository before launching vim, then nerdtree showed the icons correctly.

I understand that a deep scan would be needed in order for the icon to show, but I was thinking maybe it is possible to trigger a check whether a .git folder is contained in a certain path upon setting the current path as the root of nerdtree when pressing C (and/or other related commands).
The overhead to scan only a particular folder when the user decides to set it as the new root is, to my eyes, negligible.
Is it possible to achieve this behaviour?

**Comment by Tehnix** [comment]
I think @numbnut's solution with setting s g:NERDTreemax_depth would be the best approach to avoid scanning too deep.

Then the following cases would be supported (with depth 3):

```
root/
   +-repos-1/
   |        +-.git/ <-- Git directory
   +-subdir/
           +-repos-2/
           |        +-.git/ <-- Git directory
           +-subsubdir/
                       +-.git/ <-- Not detected (too deep)
otherdir/
        +-.git/ <-- Git directory
```

In any case, where would one start with implementing this?

**Comment by RoXuS** [comment]
+1

**Comment by Xuyuanp** [comment]
@slabua WIP #144 
btw, sorry for so long.
