### ISSUE TITLE
Need to reload nerdtree

### ISSUE THREAD

**Issue by phaalonso** [Xuyuanp/nerdtree-git-plugin#140]
When I update a file, its shows the correct symbol in nerdtree. But it shows with a wrong indentation and after a while, it corrects the indentation. How I can make to fix the indentation faster?

**Comment by Xuyuanp** [comment]
did you install `indentLine`?

**Comment by phaalonso** [comment]
nop

**Comment by Xuyuanp** [comment]
please show me you vimrc

**Comment by phaalonso** [comment]
Sure here is: https://pastebin.com/QBNV3aLA

**Comment by Xuyuanp** [comment]
You add plugins in wrong order, please try this
```vim
Plug 'scrooloose/nerdtree' |
            \ Plug 'Xuyuanp/nerdtree-git-plugin' |
            \ Plug 'ryanoasis/vim-devicons' |
            \ Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
```

**Comment by phaalonso** [comment]
Thanks, it works :smile:, thanks for the help.
