### ISSUE TITLE
PR #144 breaks the plugin on macOS 10.15.6, neovim 0.4.3

### ISSUE THREAD

**Issue by svanharmelen** [Xuyuanp/nerdtree-git-plugin#147]
I just noticed I didn't get any icons anymore. Doing a `git reset --hard 7dfb62a1d9b6233825f8df1ec96d53c472244a3a` resolved the issue, so it's somehow related to PR #144 

Let me know if there is any logging that can help or if you want me to test anything specific.

**Comment by kascote** [comment]
I have the same problem and I tracked the issue to this commit on NERDTree

https://github.com/preservim/nerdtree/commit/373a4b28e4444a5ec88ed3a81eb09073e8c92fc0#diff-ea67037158059f5e6f5239b3090f9f30

seems that `exists('#NERDTreeInit')` always returns 0

**Comment by Xuyuanp** [comment]
@kascote Yes, you are right. It should be `exists('#User#NERDTreeInit')`

**Comment by svanharmelen** [comment]
Thanks @kascote and @Xuyuanp! Let's hope for a quick fix in NERDTree then 👍

**Comment by Xuyuanp** [comment]
@svanharmelen Please see here https://github.com/preservim/nerdtree/pull/1165

**Comment by svanharmelen** [comment]
Works like a charm! Thanks @Xuyuanp!
