### ISSUE TITLE
Error detected while processing function <lambda>3[1]..390[5]..392[2]..<SNR>47_onGitWorkdirSuccessCB

### ISSUE THREAD

**Issue by rubin55** [Xuyuanp/nerdtree-git-plugin#156]
#### Self-Diagnosis

- [/] I have searched the [issues](https://github.com/Xuyuanp/nerdtree-git-plugin/issues) for an answer to my question.
- [/] I have reviewed the NERDTree documentation(README.md).
- [/] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [/] Operating System: macOs 10.14.6
- [/] Vim/Neovim version `:echo v:version`: MacVim, vim 8.2 with patches 1-1456
- [/] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 6.9.9
- [/] vimrc settings:
           

[rubins-vimrc.txt](https://github.com/Xuyuanp/nerdtree-git-plugin/files/5112883/rubins-vimrc.txt)

    - Other NERDTree-dependent Plugins
        - [x] jistr/vim-nerdtree-tabs
        - [x] ryanoasis/vim-devicons
        - [x] tiagofumo/vim-nerdtree-syntax-highlight
        - [x] Others (specify): 
    - [/] I've verified the issue occurs with only nerdtree-git-plugin installed.

#### Steps to Reproduce the Issue
1. Updated nerdtree-git-plugin through VimPlug
2. Observe error in :messages :

```
Error detected while processing function <lambda>3[1]..390[5]..392[2]..<SNR>47_onGitWorkdirSuccessCB:
line    1:
E684: list index out of range: 0
```

Note that very very sometimes, the error does not show up (1 in 10 tries approximately).

#### Current Result (Include screenshots where appropriate.)
Error:
<img width="1075" alt="Screenshot 2020-08-22 at 21 52 50" src="https://user-images.githubusercontent.com/6214491/90964555-f052ca00-e4c1-11ea-92ea-ca54c2c0ca6d.png">

#### Expected Result
No error:
<img width="1031" alt="Screenshot 2020-08-22 at 21 45 47" src="https://user-images.githubusercontent.com/6214491/90964440-ec727800-e4c0-11ea-9fda-0f31633803b9.png">

**Comment by Xuyuanp** [comment]
Related #150

**Comment by Xuyuanp** [comment]
Please update and have a try.

**Comment by rubin55** [comment]
I can confirm the issue does not occur anymore (tried about 7 times to reproduce it, all cases no error).

**Comment by Xuyuanp** [comment]
Good. I'm closing this issue. Feel free to comment if this occurs again.
