### ISSUE TITLE
Support for nesting git repos?

### ISSUE THREAD

**Issue by gz-wangxm** [Xuyuanp/nerdtree-git-plugin#158]
#### Description

I configure my neovim to automatically set the working dir to "E:\\" which is the root directory for all my projects (I am using Windows. ). That is (say): 

```plain
E:\
  -projects\
    -project1\
    -project2\
    ...
  ...
```

I want to use nerdtree-git-plugin to track changes in project1. Is there any solutions?

I tried to use ":cd projects/project1" to change my working directory, but it does not help at all - the root directory of NERDTree does not change. Then I tried to use "e" in NERDTree to change the directory, but it still does not work.

**Comment by gz-wangxm** [comment]
I just found that if I enter NERDTree after changing my working directory, it shows the right information. However, this plugin does not work as well.

**Comment by Xuyuanp** [comment]
Follow the issue template, please. I'll reopen then.
