### ISSUE TITLE
git status icons don't update when toggling NERDtree

### ISSUE THREAD

**Issue by baturevychvitalii** [Xuyuanp/nerdtree-git-plugin#159]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/Xuyuanp/nerdtree-git-plugin/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation(README.md).

#### Environment (for bug reports)
- [x] Operating System:  Linux 5.8.4-arch1-1
- [x] Vim/Neovim version `:echo v:version`: 8.2 (2019 Dec 12, compiled Aug 30 2020 08:25:15)
- [x] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 6.9.9
- [x] vimrc settings
    ```vim
    " all settings about nerdtree and other plugins
        map <c-e> :NERDTreeToggle<CR>

        " NERD tree icons and font
        set encoding=utf8

        " Use NERD fonts with NERDTree git
        let g:NERDTreeGitStatusUseNerdFonts = 1
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [x] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ ] Others (specify): 
    - [ ] I've verified the issue occurs with only nerdtree-git-plugin installed.

#### Steps to Reproduce the Issue
1. open file, tracked by git, unchanged from last commit.
2. close NERDtree
3. modify and save the file
4. toggle NERDtree

#### Current Result (Include screenshots where appropriate.)
![2020-08-31-01:57:21-scr](https://user-images.githubusercontent.com/44236584/91672235-8b384d80-eb2d-11ea-8356-fc49cc32a764.png)

#### Expected Result
![2020-08-31-01:56:59-scr](https://user-images.githubusercontent.com/44236584/91672239-912e2e80-eb2d-11ea-8333-d892c7255cfd.png)

**Comment by Xuyuanp** [comment]
Yes. This is a known issue I have no idea how to fix currently.

**Comment by baturevychvitalii** [comment]
I found a quickfix. Not a solution but works:
as mentioned in bug report message i have this line
map <c-e> :NERDTreeToggle<CR>
to toggle nerdtree.
I changed it to following:
#map <c-e> :NERDTreeToggle<CR>:NERDTreeRefreshRoot<CR>
Now it works fine

**Comment by baturevychvitalii** [comment]
I came up with a quickfix:
As mentioned in bug report, I have following line in my ~/.vimrc:
#### map \<c-e> :NERDTreeToggle\<CR>
to toggle nerd tree (cause i don't need to see it all the time)
I changed it to
#### map \<c-e> :NERDTreeToggle\<CR>:NERDTreeRefreshRoot\<CR>
seems like it has fixed the issue for me, and whenever i toggle nerd tree git icons are up to date

**Comment by Xuyuanp** [comment]
Wow!

I'll come up with a final solution, just need some time.

**Comment by dasraab** [comment]
same problem here. glad to hear that you're working on it! love this plugin!

**Comment by Xuyuanp** [comment]
Hi guys
Please update and have a try.

**Comment by baturevychvitalii** [comment]
Thanks, works perfect!
