### ISSUE TITLE
Extra symbols (glyphs) do work - but not in the environments I need them to...

### ISSUE THREAD

**Issue by Magicrafter13** [Xuyuanp/nerdtree-git-plugin#166]
#### Self-Diagnosis

- [X ] I have searched the [issues](https://github.com/Xuyuanp/nerdtree-git-plugin/issues) for an answer to my question.
- [X ] I have reviewed the NERDTree documentation(README.md).
- [X ] I have searched the web for an answer to my question.

#### State Your Question

I know the title is a little vague, but either way, here goes: I wasn't seeing the proper glyphs for the files in the git repo I was working in, everything was just a placeholder (rectangle) for symbols that can't be displayed. I tried in command prompt, powershell (and powershell-core), Ubuntu via WSL, and all the previous terminals, but running in Windows Terminal.

So, I begin to investigate, and from what I gather, as far as command prompt is concerned, whatever it uses to display characters wasn't designed for... well, whatever it needs to do this. But, I read that you could use "patched" fonts with powershell/wt, so I tried one ('Hack', if it matters), and it still didn't work. I don't fully remember everything I did, but I did (what I thought was) everything the nerd fonts readme.md stated.

This morning for the hell of it, I connect to my server from my phone, using Termius and JuiceSSH (don't ask why I have both), and while Juice did the same thing, Termius actually showed the glyphs! As far as I'm concerned, that rules out any issues on the server side (or in other words, with my ViM setup).

I went back to searching around online, checked out a few more things, but I'm just not seeing it. I believe I read that you could use Microsoft's Cascadia font, as there was one that was compatible with "PowerLine", which I originally thought was like, the name of the extra glyphs :) , but now I'm thinking they were just referring to the plugin. Still, I modified the settings json file of WT to use Cascadia Mono( and Code) PL, but to no avail. So at this point I have no idea what to do, because I'm still not even sure what the _problem_ is.

Final bits:
Nothing wrong with NERDTree, works fine.
It worked in Termius, so this isn't that important, but I did try this on the actual server after plugging a monitor and keyboard into it, and the glyphs still didn't work, but to be fair a ton of things didn't quite look right, and I think that's just due to how basic the non-gui terminal is. Hell, it only supports 16 colors...
Also, if it wasn't obvious by what I've already said, I'm not running ViM locally, I'm running it over ssh, from a Windows environment. I saw someone mentioning a setting in PuTTY that fixed this (or a similar?) issue for them, but I'm not using PuTTY, nor am I going to use it. On Windows 10, with WT/PowerShell/WSL (and cmd).

**Comment by Xuyuanp** [comment]
I'm not sure what's wrong with your env. I could share my WSL config with you later.

**Comment by Xuyuanp** [comment]
my font is  ` "fontFace": "FiraCode Nerd Font Mono"`

**Comment by Magicrafter13** [comment]
> my font is ` "fontFace": "FiraCode Nerd Font Mono"`

Currently using `"fontFace": "Cascadia Mono PL"`, first one I tried was Hack (which is a Nerd Font)

**Comment by Magicrafter13** [comment]
![image](https://user-images.githubusercontent.com/29127566/94618933-d8a8f700-0260-11eb-862c-b744825e5ba0.png)

I whipped up a quick little c program (based on something I saw on an issue in the powerline repo). Don't ask why I did it in C, I couldn't remember how to output unicode in bash haha.

Anyway, these special characters seem to work fine (in Windows Terminal, Powershell and Powershell-core displayed a couple of the symbols, and command prompt couldn't display any of them). Yet, they still just show up as boxes when I'm inside ViM...

Actually, I just sent the output of `test` to a text file, then opened it in ViM... the symbols appeared. So, I'm going to assume that these glyphs are unrelated to the ones that nerdtree-git is trying to show...
![image](https://user-images.githubusercontent.com/29127566/94619225-5cfb7a00-0261-11eb-85f3-4034ac245787.png)

**Comment by Magicrafter13** [comment]
Nevermind, apparently I misunderstood the instructions in the README.

This plugin works fine now:
![image](https://user-images.githubusercontent.com/29127566/94619634-135f5f00-0262-11eb-8de6-b5e030f818fa.png)

All I did was get rid of this line in my `.vimrc`:  
`let g:NERDTreeGitStatusUseNerdFonts = 1`

Now I just need to get vim-devicons working heh...
