### ISSUE TITLE
nerdtree-git-plugin not working with the latest nerdtree(6.9.10) on vim7.4

### ISSUE THREAD

**Issue by shiluotang** [Xuyuanp/nerdtree-git-plugin#172]
#### Self-Diagnosis
- [x] I have searched the [issues](https://github.com/Xuyuanp/nerdtree-git-plugin/issues) for an answer to my question.
- [ ] I have reviewed the NERDTree documentation(README.md).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [linux] Operating System:
- [ ] vimrc settings
    ```vim
    " all settings about nerdtree and other plugins

    Plug 'preservim/nerdtree'
    Plug 'Xuyuanp/nerdtree-git-plugin'
    ```
    vim (7.4, patches: 1-52, Extra patches: 8.0.0056)
    nerdtree (6.9.10)
    nerdtree-git-plugin (01b84c6)
    - Other NERDTree-dependent Plugins
        - [ ] Others (specify):
    - [x] I've verified the issue occurs with only `nerdtree-git-plugin` installed.
- [x] Copy-Paste `call gitstatus#doctor#Say()` outputs

        Error detected while processing /home/xxxxx/.vim/plugged/nerdtree-git-plugin/au
        toload/gitstatus/doctor.vim:                                                    
        line   21:                                                                      
        E121: Undefined variable: v:true                                                
        E116: Invalid arguments for function type(v:true), 'NULL': type(v:null) }       
        E15: Invalid expression: { 'NUMBER': type(0), 'STRING': type(''), 'FUNCREF': typ
        e(function('tr')), 'LIST': type([]), 'DICT': type({}), 'FLOAT': type(0.0), 'BOOL
        ': type(v:true), 'NULL': type(v:null) }                                         
        line   24:                                                                      
        E15: Invalid expression: > string(nbr) }                                        
        E15: Invalid expression: { nbr -> string(nbr) }                                 
        line   25:                                                                      
        E15: Invalid expression: > printf("'%s'", str) }                                
        E15: Invalid expression: { str -> printf("'%s'", str) }                         
        line   26:                                                                      
        E15: Invalid expression: > string(fn) }                                         
        E15: Invalid expression: { fn  -> string(fn) }                                  
        line   27:                                                                      
        E15: Invalid expression: > s:prettifyList(lst, '  \ ', 0, '  ') }               
        E15: Invalid expression: { lst -> s:prettifyList(lst, '  \ ', 0, '  ') }        
        line   28:                                                                      
        E15: Invalid expression: > s:prettifyDict(dct, '  \ ', 0, '  ') }

#### Steps to Reproduce the Issue
1. :NERDTreeToggle<CR>

#### Current Result (Include screenshots where appropriate.)

    NERDTree: Please wait, caching a large dir ...
    Error detected while processing function 262..263..246..249..213..211..323:
    line    5:
    E725: Calling dict function without Dictionary: 331
    Error detected while processing function 262..263..246..249..213:
    line   25:
    E171: Missing :endif
    Error detected while processing function 262..263:
    line   14:
    E171: Missing :endif
    Press ENTER or type command to continue

#### Expected Result

**Comment by Xuyuanp** [comment]
vim is too old.

**Comment by feddischson** [comment]
I discovered the same issue and I have the latest vim available on Gentoo.

```
VIM - Vi IMproved 8.2
Included patches: 1-360
Modified by Gentoo-8.2.0360
```
