### ISSUE TITLE
all files have * after their name

### ISSUE THREAD

**Issue by amirhosseinak20** [Xuyuanp/nerdtree-git-plugin#177]
All my files has a * after their name and not colored right

my vim configs are in here [init.vim](https://github.com/amirhosseinak20/nvim-config)
#### Copy-Paste `call gitstatus#doctor#Say()` outputs
![Screenshot_20201215_124027](https://user-images.githubusercontent.com/44077252/102194670-d4d95800-3ed2-11eb-9cb4-9b07df95eddf.png)
![Screenshot_20201215_124011](https://user-images.githubusercontent.com/44077252/102194717-e0c51a00-3ed2-11eb-9f76-275663b3ef79.png)

#### Current Result (Include screenshots where appropriate.)
![Screenshot_20201215_123705](https://user-images.githubusercontent.com/44077252/102194751-e9b5eb80-3ed2-11eb-948d-287d93fb0619.png)
![Screenshot_20201215_124206](https://user-images.githubusercontent.com/44077252/102194866-0f42f500-3ed3-11eb-94b0-299c6c1f0fa7.png)

**Comment by Xuyuanp** [comment]
set option `g:NERDTreeGitStatusShowIgnored` to `0`

**Comment by amirhosseinak20** [comment]
I did that but i still have this issue

**Comment by Xuyuanp** [comment]
Sorry, I think I've misunderstood your issue. The `*` after the python scripts is a feature of nerdtree. It highlights the executable files and adds `*` as suffix.

**Comment by amirhosseinak20** [comment]
it appears after every file, not only python files. in above photo you can see appeared in the txt file also

**Comment by Xuyuanp** [comment]
`ls -l`. you will see some lines like `-rwxr-xr-x`. The `x` indicates this file is `executable`.

**Comment by amirhosseinak20** [comment]
i guess there is a problem with ntfs file system after i checked that, in ext4 it was shown correctly but in ntfs file system there is issue
