### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by leehc257** [Xuyuanp/nerdtree-git-plugin#180]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/Xuyuanp/nerdtree-git-plugin/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation(README.md).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System:  CentOS Linux release 7.7.1908 (Core)
- [x] vimrc settings
    ```vim
    " all settings about nerdtree and other plugins
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [x] ryanoasis/vim-devicons
        - [x] tiagofumo/vim-nerdtree-syntax-highlight
        - [ ] Others (specify):
    - [x] I've verified the issue occurs with only `nerdtree-git-plugin` installed.
- [ ] Copy-Paste `call gitstatus#doctor#Say()` outputs

#### Steps to Reproduce the Issue
1. I installed plugin, then not working nerdtree.
2. vim version : 8.0
3. git version : 2.22.0

i want to use this plugin for convenience. 

#### Current Result (Include screenshots where appropriate.)

![1](https://user-images.githubusercontent.com/55521614/104254713-bb6c0180-54ba-11eb-97b9-8d5dd3352ca0.JPG)
this situation : enter vim( :e.)
![2](https://user-images.githubusercontent.com/55521614/104254716-be66f200-54ba-11eb-96af-81dca8ec06e5.JPG)
my folder structure
![3](https://user-images.githubusercontent.com/55521614/104254722-c030b580-54ba-11eb-8408-81d99bae3540.JPG)
this situation : move to ..(up a dir)

& my vimrc

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" plugin
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
call plug#begin('~/.vim/plugged')

Plug 'preservim/nerdtree'                   "nerdtree
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'ryanoasis/vim-devicons'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'

call plug#end()
set encoding=utf-8
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"Plug 'Xuyuanp/nerdtree-git-plugin'
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"let g:loaded_nerdtree_git_status = 1
"let g:NERDTreeGitStatusShowClean = 1 " default: 0
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:NERDTreeFileExtensionHighlightFullName = 1
let g:NERDTreeExactMatchHighlightFullName = 1
let g:NERDTreePatternMatchHighlightFullName = 1
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" 'preservim/nerdtree'
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
nmap <Leader>r :NERDTreeFocus<cr> \| R \| <c-w><c-p>
let g:NERDTreeGitStatusUseNerdFonts = 1
let g:NERDTreeGitStatusIndicatorMapCustom = {
                \ 'Modified'  :'✹',
                \ 'Staged'    :'✚',
                \ 'Untracked' :'✭',
                \ 'Renamed'   :'➜',
                \ 'Unmerged'  :'═',
                \ 'Deleted'   :'✖',
                \ 'Dirty'     :'✗',
                \ 'Ignored'   :'☒',
                \ 'Clean'     :'✔︎',
                \ 'Unknown'   :'?',
                \ }
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

**Comment by Xuyuanp** [comment]
Hi, can you translate the Korean text in the pics?

**Comment by lhc257** [comment]
yellow line :      12 line : 
red lie :             E475: invalid arguments : env

**Comment by leehc257** [comment]
yellow line :         12 line : 
red line :          E475:  Invalid argument : env

**Comment by Xuyuanp** [comment]
Please upgrade your vim(>= 8.0.0902)
> Patch 8.0.0902
  Problem:    Cannot specify directory or environment for a job.
  Solution:   Add the "cwd" and "env" arguments to job options. (Yasuhiro
              Matsumoto, closes #1160)

**Comment by leehc257** [comment]
thanks~!!!!!
