### ISSUE TITLE
Can I change the color of git icon generated by this plugin?

### ISSUE THREAD

**Issue by winston0410** [Xuyuanp/nerdtree-git-plugin#185]
#### Self-Diagnosis

- [ yes ] I have searched the [issues](https://github.com/Xuyuanp/nerdtree-git-plugin/issues) for an answer to my question.
- [ yes ] I have reviewed the NERDTree documentation(README.md).
- [ yes ] I have searched the web for an answer to my question.

#### State Your Question

Based on the documentation, I know I can change the icon used for denoting different git status, but is it possible for me to change their color? I cannot find any documentation on this in the README

**Comment by Xuyuanp** [comment]
Yes, you can change color by setting this option:

```vim
let g:NERDTreeGitStatusHighlightingCustom = [
            \ ['Unmerged',  'Function'],
            \ ['Modified',  'Special'],
            \ ['Staged',    'Function'],
            \ ['Renamed',   'Title'],
            \ ['Unmerged',  'Label'],
            \ ['Untracked', 'Comment'],
            \ ['Dirty',     'Tag'],
            \ ['Deleted',   'Operator'],
            \ ['Ignored',   'SpecialKey'],
            \ ['Clean',     'Method'],
            \ ]
```

**Comment by RobertBrunhage** [comment]
@Xuyuanp Could you give an example of this? I've tried setting hex colors there but that is not setting any colors.

**Comment by Xuyuanp** [comment]
Sorry, I was hospitalized recently, will show you some examples later.

**Comment by calvh** [comment]
@RobertBrunhage I found the highlighting function in `autoload/gitstatus/job.vim`. It looks like the function given can only set colors based on predefined groups. Those groups are defined by your colorscheme. For example, in [this monokai theme](https://github.com/crusoexia/vim-monokai) there is this line: 
`call s:h("SpecialKey",    { "fg": s:pink })`
which defines the group SpecialKey to be pink, which is defined as `let s:pink        = { "gui": "#F92772", "cterm": "197" }`.
