### ISSUE TITLE
error occurs when start nerdtree

### ISSUE THREAD

**Issue by H-Yin** [Xuyuanp/nerdtree-git-plugin#190]
Error detected while processing function 206..207..190..193..157..155..266:
line    5:
E725: Calling dict function without Dictionary: 274
Error detected while processing function 206..207..190..193..157:
line   25:
E171: Missing :endif
Error detected while processing function 206..207:
line   14:
E171: Missing :endif

**Comment by Xuyuanp** [comment]
Sorry for the inconvenience, but I have to close this issue because it doesn't use the issue template.

Please feel free to issue a new one.
