### ISSUE TITLE
Colored icons

### ISSUE THREAD

**Issue by Curs3W4ll** [Xuyuanp/nerdtree-git-plugin#192]
Hi there !

It could be really nice if we could add colors to icons (green for untracked, red for deleted....)
And would be even better if we could personnalized them
:)

**Comment by tom-spalding** [comment]
@Curs3W4ll you can swap out the default icons with `NERDTreeGitStatusIndicatorMapCustom`, or use the dev icon support.

https://github.com/Xuyuanp/nerdtree-git-plugin#faq

**Comment by Curs3W4ll** [comment]
I guess I wasn't clear enough, I doesn't mean to change the icon, just keep the icon but change the color of it, like, the color of the 'section' where the plugin write the icon
If it is not possible, I guess I will forget it :crying_cat_face:

**Comment by tom-spalding** [comment]
Maybe give editing this plugin a shot @Curs3W4ll, and let us know how it goes?
