### ISSUE TITLE
Only works when nvim is run with directory argument

### ISSUE THREAD

**Issue by mmrzax** [Xuyuanp/nerdtree-git-plugin#194]
- [x] I have searched the [issues] for an answer to my question.
- [x] I have searched the web for an answer to my question.

NVIM v0.4.4
linux
shell=zsh
installed with cloning the repo to ~/.local/share/nvim/site/pack/mrxplugs/start/

Not works when :
1- directly run the nvim or execute nvim from terminal.
2- `nvim ~/aGitProject/file.js`

Only works when :
`nvim ~/aGitProject/`

**Comment by Swarthe** [comment]
Have you tried changing to the project's directory before running `nvim` on a file?

**Comment by mmrzax** [comment]
> Have you tried changing to the project's directory before running `nvim` on a file?

If you mean to change the directory before launching nivm and run nvim in the project path (`nvim <ProjectPath>`),
yes it works but I want to check another project from the Nerdtree window while working and in this case it's doesn't show the status of other Git projects. (even by refreshing Nerdtree)
This means that for each project I have to separately run nvim in that directory.
Of course, I thought this was a bug, I apologize if this is how the plugin works.
