### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by ntanhpro1221** [Xuyuanp/nerdtree-git-plugin#200]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/Xuyuanp/nerdtree-git-plugin/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation(README.md).
- [x] I have searched the web for an answer to my question.

#### State Your Question
Hello,i added it in my init.vim but nothing happen
-Init.vim:

set number
set mouse=a

call plug#begin('C:\Users\Ntanh\AppData\Local\nvim\autoload\plugged')

"-----------------<{FOR_FAST_CODING}>-------------------
Plug 'gosukiwi/vim-smartpairs'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
"-----------------<{FILE_MANAGEMENT}>--------------------
Plug 'preservim/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'ryanoasis/vim-devicons'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
"-----------------<{STATUS_BAR}>--------------------
"Plug 'itchyny/lightline.vim'
"Plug 'mengelbrecht/lightline-bufferline'
"Plug 'Ap/vim-buftabline'
Plug 'crispgm/nvim-tabline'
"---------------------<{THEME}>-------------------------
Plug 'tanvirtin/monokai.nvim'

call plug#end()
colorscheme monokai_pro

"---------------------<{COPY_PATE}>-------------------------
vmap "+y

"---------------------<{EXTENDED_SETTINGS}>-------------------------
let nvim_settings_dir = 'C:\Users\Ntanh\AppData\Local\nvim\settings'
execute 'source '.nvim_settings_dir.'_nerdtree.vim'
execute 'source '.nvim_settings_dir.'_airline.vim'

I dont know what im missing.thanks

**Comment by Loureas** [comment]
I support this issue. Also added the plugin using VimPlug but nothing happens.
Also here is the config:
```vim
call plug#begin()

" Visual plugins
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ryanoasis/vim-devicons'
Plug 'kyazdani42/nvim-web-devicons'
Plug 'akinsho/bufferline.nvim', {'branch': 'main'}
Plug 'yggdroot/indentline'

Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'ap/vim-css-color'
Plug 'mattn/emmet-vim'
Plug 'tpope/vim-fugitive'
Plug 'mhinz/vim-signify'
Plug 'airblade/vim-gitgutter'
Plug 'jiangmiao/auto-pairs'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'mg979/vim-visual-multi', {'branch': 'master'}
Plug 'instant-markdown/vim-instant-markdown', {'for': 'markdown'}
Plug 'nvim-treesitter/nvim-treesitter'
Plug 'Vimjas/vim-python-pep8-indent'

" NERDTree
Plug 'preservim/nerdtree' | Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
call plug#end()
```
