### ISSUE TITLE
Wrong indicator for the directory that contains the opened file

### ISSUE THREAD

**Issue by johnugeorge** [Xuyuanp/nerdtree-git-plugin#23]
When I open a file(inside a git repository), I can see that directory that contains the file is always shown as Dirty.  Rest all indicators are correct except the directory that contains the file.

**Comment by Xuyuanp** [comment]
Please show me the `git status -s` output.

**Comment by johnugeorge** [comment]
it is clean. git status -s gives empty result.  I can provide more debug info if you provide hints

**Comment by Xuyuanp** [comment]
Do you have any other plugin that modified the file while opening?

**Comment by johnugeorge** [comment]
Here are the plugins that I use. I don't see any plugin that modifies the file while opening.
Plugin 'https://github.com/Valloric/YouCompleteMe.git'
Plugin 'scrooloose/nerdtree'
Plugin 'bling/vim-airline'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'flazz/vim-colorschemes'
Plugin 'scrooloose/syntastic'

When I open the file vi sample/sample.yaml, git status -s shows vi temp file sample/.sample.yaml.swp . Is this due to temp file creation?

**Comment by Xuyuanp** [comment]
Yes, it is. You could use `set backupdir=/you/path/` to set the backup files to another location, or use `set nobackup` to disable backup file, or add `.swp` into NERDTreeIgnore to ignore these files in NERDTree.

**Comment by johnugeorge** [comment]
Thanks. It worked!
