### ISSUE TITLE
Filemode changes cause incorrect GIT indicators

### ISSUE THREAD

**Issue by eknowlton** [Xuyuanp/nerdtree-git-plugin#24]
Awesome vim plugin, thanks very much.

I've updated the file mode on a entire project folder and then I used the `git config` tool to ignore file mode changes.

`git config core.fileMode false`

Now when I run `git status` it shows what I expected as a result....
![screen shot 2015-08-19 at 10 50 42 am](https://cloud.githubusercontent.com/assets/544791/9361471/9dc92a82-4669-11e5-887e-b692a1d81d60.png)

But when I open up `vim`, it shows the '*' next to all of my files...
![screen shot 2015-08-19 at 10 51 03 am](https://cloud.githubusercontent.com/assets/544791/9361472/9dcae822-4669-11e5-80d3-f84cf63b0b93.png)

I don't think this is what I should be seeing. Please let me know if I'm doing something wrong, otherwise maybe its a bug.

**Comment by Xuyuanp** [comment]
Hi, it seems that you have some untracked files under the `cron/v2/googleads-php-lib/` dir. There is no matter with file mode.

**Comment by Xuyuanp** [comment]
Oh! Do you mean the '*' after the file names?

That was a feature of nerdtree which means the file is executable.

The git status indicator provided by nerdtree-git-plugin is that in `[]` before file or dir name.

**Comment by eknowlton** [comment]
All the files should be tracked, minus some changes in google-ads-php-lib really.

Ya, that is my bad, I thought the bold orange filename and * were untracked files, apparently I did have the mode to executable. 

That must be what i'm seeing. Thanks for the reply @Xuyuanp. Greatly appreciated.

**Comment by eknowlton** [comment]
What means untracked? Is there anywhere to see this, or are they same as the previous project?

**Comment by Xuyuanp** [comment]
[Here is all you should know](https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository)

**Comment by eknowlton** [comment]
Thanks, I believe I should be looking into nerdtree itself for what i'm trying to look for.
