### ISSUE TITLE
how does it work,is there any necessary config in vimrc？

### ISSUE THREAD

**Issue by wsdjeg** [Xuyuanp/nerdtree-git-plugin#25]

**Comment by Xuyuanp** [comment]
It is a plguin of nerdtree, so it should be used with nerdtree. Please read the README to see how to install them. And no additional config is needed. I will work while you opening nerdtree under a git repo dir.

**Comment by wsdjeg** [comment]
thank you

**Comment by wsdjeg** [comment]
![2015-09-10 16-27-48](https://cloud.githubusercontent.com/assets/13142418/9783717/0f810c00-57d9-11e5-9a40-48d449917277.png)

**Comment by wsdjeg** [comment]
but There is little space left of the icon

**Comment by Xuyuanp** [comment]
A little weird... Have you tried to use another font family?

**Comment by wsdjeg** [comment]
no  my font is ubuntu system default font

**Comment by Xuyuanp** [comment]
Sorry, I dont have ubuntu env, but it looks like that it is because of the font you used couldn't render the indicators correctly.

**Comment by wsdjeg** [comment]
ok i undersatant ,and This does not affect the work
