### ISSUE TITLE
.vimrc customizable indicators?

### ISSUE THREAD

**Issue by tikiking1** [Xuyuanp/nerdtree-git-plugin#27]
My font of choice doesn't have all the Unicode indicators this plugin uses by default. I tried adding `let g:NERDTreeIndicatorMap.Untracked = "*"` to the bottom of my `.vimrc`, but then I get `E121: Undefined variable: g:NERDTreeIndicatorMap`.

**Comment by Xuyuanp** [comment]
You could set custom indicators in this way
```viml
let g:NERDTreeIndicatorMap = {
            \ "Modified"  : "o",
            \ "Staged"    : "+",
            \ "Untracked" : "*",
            \ "Renamed"   : "➜",
            \ "Unmerged"  : "═", 
            \ "Deleted"   : "X",
            \ "Dirty"     : "x",
            \ "Clean"     : "@",
            \ "Unknown"   : "?"
            \ }
```

But you will lost syntax highlight of these indicators.

**Comment by Xuyuanp** [comment]
Thanks to @PickRelated  #26

**Comment by PickRelated** [comment]
@Xuyuanp, my pleasure! You've made it possible, I just corrected for proper syntax highlight.

**Comment by PickRelated** [comment]
@Xuyuanp, we have a little problem. I put `\` in `modified` and `dirty` reg expressions for a reason. They allow to use `~` symbol which is very likely to come up. It forbids to use several symbols in this case, but that would be `_` and `+` which are not likely to be set up for modified or dirty option.
Please consider adding escaping characher at lines 227 and 281.
