### ISSUE TITLE
Plugin not work on vundle install

### ISSUE THREAD

**Issue by gunlinux** [Xuyuanp/nerdtree-git-plugin#28]
Plugin crush nerdtree plugin

## simplified .vimrc
```vim
set nocompatible                " choose no compatibility with legacy vi
filetype off                    " For plugins
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
call vundle#end()
```
full .vimrc
https://gist.github.com/gunlinux/e9090fc89f9601b608ac

## start error log
```bash
Error detected while processing function <SNR>31_NERDTreeGitStatusKeyMapping:
line    2:
E117: Unknown function: g:NERDTreeAddKeyMap
line    3:
E117: Unknown function: g:NERDTreeAddKeyMap
```

## nerdtree run error log
```bash
Error detected while processing function 194..195..180..183..146..144..240..NERDTreeGitStatusRefreshListener..g:NERDTreeGetGitStatusPrefix:
E117: Unknown function: g:nerdtree#runningWindows
E15: Invalid expression: g:nerdtree#runningWindows()
Error detected while processing function 194..195..180..183..146:
E171: Missing :endif
Error detected while processing function 194..195:
E171: Missing :endif
```

```bash
rm -rf ~/.vim
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim
:PluginInstall
```

**Comment by Xuyuanp** [comment]
your `vim --version` result?

**Comment by gunlinux** [comment]
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Aug 22 2015 15:56:25)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses

**Comment by Xuyuanp** [comment]
Update again please.

Sorry I forgot to test with old version vim.

**Comment by gunlinux** [comment]
No problem, thank you, now works fine.
