### ISSUE TITLE
pathogen上不好用？

### ISSUE THREAD

**Issue by DeanSinaean** [Xuyuanp/nerdtree-git-plugin#29]
试了几种方法，没用起来。

**Comment by Xuyuanp** [comment]
报什么错了吗

**Comment by logankoester** [comment]
Works for me with Pathogen, but I did need to `git pull` the latest master branch commits in my `~/.vim/bundle/nerdtree` local clone.

**Comment by Xuyuanp** [comment]
Nerdtree got a very huge upgrade last year. So if you haven't updated it for a long time, there may be something wrong with the nerdtree-git-plugin.
