### ISSUE TITLE
Works only with sudo

### ISSUE THREAD

**Issue by inebritov** [Xuyuanp/nerdtree-git-plugin#30]
I install this plugin by "junegunn/vim-plug". Then I run vim in my project folder:
![gitgutter](https://cloud.githubusercontent.com/assets/6717482/10024733/501601da-6161-11e5-9481-a35f32b3ef28.png)

There is no changes. But when I copy .vimrc to /root folder (and install plugins there) after executing "sudo vim" plugin works:
![sudo](https://cloud.githubusercontent.com/assets/6717482/10024798/89709544-6161-11e5-94fe-d4c19cda1f68.png)

My system is debian 8 x64. Folder .vim/ is readable and writable by user. You can see my .vimrc here: https://github.com/inebritov/dotfiles/blob/master/.vimrc

**Comment by Xuyuanp** [comment]
Try to update nerdtree first.

**Comment by inebritov** [comment]
nerdtree head is **0b44415a3302030b56755cc1135ca9ca57dc1ada**. nerdtree-git-plugin head is **932552ee295971cfb202c3b360319cb56e4ba6f0**. Commits are latest in their repositories.

**Comment by Xuyuanp** [comment]
What's the difference between .vim under /root and that under your HOME?

**Comment by inebritov** [comment]
/root/.vimrc is just copy of ~/.vimrc. All plugins (in home and in /root) was installed by :PlugInstall.

**Comment by Xuyuanp** [comment]
Show me the results of `git status -s` and `sudo git status -s` under your work directiory, please.

**Comment by inebritov** [comment]
Sure. For clarity, I stash the work changes and added a blank line in the file 'manage.py'.
```sh
~/workspace/javelina (third) $ git status -s
 M manage.py
~/workspace/javelina (third) $ sudo git status -s
 M manage.py
```

Changes are visible only with sudo.

vim:
![vim](https://cloud.githubusercontent.com/assets/6717482/10121731/2f71e638-6503-11e5-827a-7a74ac1558db.png)

sudo vim:
![sudovim](https://cloud.githubusercontent.com/assets/6717482/10121733/3766f2e8-6503-11e5-8ffd-c1a8d703c498.png)

**Comment by inebritov** [comment]
I install nerdtree-git-plugin on Ubuntu 14.04, Fedora 22 and it works. I did not find the problem solution in Debian. If someone is interested, the image of my virtual machine can be found ![here](https://drive.google.com/uc?export=download&id=0B_pn9sF-OG0ZcklINmlGZm9MWEk) (Debian 8 x64: 600MB zipped, 20GB unzipped, username: user, password: 123456)

**Comment by Xuyuanp** [comment]
This was so weird! I couldn't find why now. I would try to use your image to have a test.

**Comment by inebritov** [comment]
The problem was in git config color status option. Solves solved by adding "-c color.status=false" to git status call.
