### ISSUE TITLE
Error when open nerdtree

### ISSUE THREAD

**Issue by Crandel** [Xuyuanp/nerdtree-git-plugin#32]
When I open nerdtree with this plugin it`s return errors, shown below

Error detected while processing function 
177[2]..178[22]..181[7]..144[9]..142[36]..238[4]..NERDTreeGitStatusRefreshListener[2]..NERDTreeGitStatusRefresh:
line    6:
E484: Can't open file /tmp/vZEZ6gM/1

I install this plugins using pathogen and last fresh version from github. 
Arch linux x64

I found problem.

I use **fish** instead of bash and when I add

```vim
if &shell =~# 'fish$'
    set shell=sh
endif
```
into my **.vimrc**, everything works fine

**Comment by Xuyuanp** [comment]
This was because that vim couldn't run `system` command in fish.

So what you did is the right way.

**Comment by Crandel** [comment]
I think this can be added to **FAQ**

**Comment by bogem** [comment]
@Crandel +
Thanks for solve the problem

**Comment by marco-silva0000** [comment]
I have this exact problem, but i cant fix it with those lines on .vimrc
