### ISSUE TITLE
Surrounding [] not shown in tmux

### ISSUE THREAD

**Issue by matthiasbeyer** [Xuyuanp/nerdtree-git-plugin#34]
I don't know whether your `[` and `]` are special UTF-8 characters or whatever, but these characters are not printed in tmux for me. Would be nice to be fixed.

Also, if I have

```
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "mod",
"...
}
```

thinks like `some/path/some/bla/mod.rs` are highlighted, which is clearly not what we want here, right? Would be nice if you'd fix these!

Anyways: Great plugin, just started using nerdtree and already in love with this plugin!

**Comment by Xuyuanp** [comment]
Screenshots please.

**Comment by matthiasbeyer** [comment]
![2015-10-28-152506_179x388_scrot](https://cloud.githubusercontent.com/assets/427866/10792858/c49d30c0-7d8e-11e5-975b-a514c7170b84.png)

(You see the ``r'' character beeing highlighted everywhere?)
With this settings:

```viml
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "mod",
    \ "Staged"    : "=",
    \ "Untracked" : "untr",
    \ "Renamed"   : "r",
    \ "Unmerged"  : "unmerg",
    \ "Deleted"   : "del",
    \ "Dirty"     : "-",
    \ "Clean"     : " ",
    \ "Unknown"   : "?"
    \ }

```
