### ISSUE TITLE
Other vcs support

### ISSUE THREAD

**Issue by inebritov** [Xuyuanp/nerdtree-git-plugin#36]
What about adding another vcs? Is it possible to add mercurial? `hg status` output is similar to `git status -s`.

**Comment by Xuyuanp** [comment]
Sorry for waiting so long.

I'm not familiar with `hg`, and I have not much time to do this work. If you could implement this feature, feel free to pull request.

**Comment by orao** [comment]
Mercurial support seems to have been implemented independently in a fork at [f4t-t0ny/nerdtree-hg-plugin](https://github.com/f4t-t0ny/nerdtree-hg-plugin).
