### ISSUE TITLE
How to set NERDTree

### ISSUE THREAD

**Issue by shiro-saber** [Xuyuanp/nerdtree-git-plugin#37]
How I set NERDTree to start at the same time of vim from .vimrc?

And what is yout color scheme?

**Comment by Xuyuanp** [comment]
See in NERDTree faq:

>  How can I open a NERDTree automatically when vim starts up?

Stick this in your vimrc: autocmd vimenter * NERDTree

> How can I open a NERDTree automatically when vim starts up if no files were specified?

Stick this in your vimrc

```
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
```

My colorscheme in the gif is molokai.

**Comment by shiro-saber** [comment]
Thanks :)
