### ISSUE TITLE
Add "--ignore-submodules" to the git-status query

### ISSUE THREAD

**Issue by ssiccha** [Xuyuanp/nerdtree-git-plugin#39]
I have a few submodules in my .vimrc directory that make my git-status query quite slow so I aliased them to include --ignore-submodules.

The nerdtree-git-plugin queries the git directory without the ignore parameter, which makes my NERDTree extremely unresponsive. Doing this to line 76 fixed it for me:
```
let l:statusesStr = system('cd ' . l:root . ' && git -c color.status=false status -s --ignore-submodules')
```
Is this safe to include into the repo? :) The plugin only uses git-status to query the information about the current directory anyways, doesn't it?

**Comment by ssiccha** [comment]
Thanks :)

**Comment by Xuyuanp** [comment]
Have fun!
