### ISSUE TITLE
Not works when CD

### ISSUE THREAD

**Issue by Fuelen** [Xuyuanp/nerdtree-git-plugin#42]
Hi. This plugin works only when I add
`cd directrory_with_git`
to my `vimrc` file.
But I work not only with 1 directory and when I change directory in NERDtree to another project with git (press `cd` and then `C` to enter), then there are no indicators near files and directories.

**Comment by Xuyuanp** [comment]
This plugin displays indicators under the root of NERDTree. As the latest version of NERDTree, `cd` command in vim doesn't change the root.

**Comment by Fuelen** [comment]
@Xuyuanp nevertheless, `C` changes tree root.

**Comment by Xuyuanp** [comment]
Got it. I found out what's the matter. That's because that the root won't be auto updated as the  `NERDTreeRoot` var has been replaced by `NERDTree.root`, see in #41.

Just update both `nerdtree` and this one, everything is OK.

**Comment by Fuelen** [comment]
Thank you! :)
