### ISSUE TITLE
Usage documentation

### ISSUE THREAD

**Issue by jbouhier** [Xuyuanp/nerdtree-git-plugin#43]
Hi,

I've installed nerdtree + nerdtree-git-plugin with Vundle.
When I open nerdtree in a git directory and make changes in a file, nothing happend.
Where do I go from here ?

P.S: What are your other plugins in the README.md gif ? powerline + some kind of git commit plugin ?

**Comment by Xuyuanp** [comment]
Is `git` command in you `$PATH`? And please show me the output of `git status -s`.

P.S: My vim config is in [vimrc](https://github.com/Xuyuanp/vimrc).

**Comment by jbouhier** [comment]
Yes, git is in my $PATH.

Here's the output of `git status -s`:
➜  test_repo git:(master) ✗ git st -s
 M doc/admin
 M main.c
?? doc/.admin.swp
➜  test_repo git:(master) ✗

I think I just found why I thought it didn't work. I was expecting to get the `+` appear before line number when making changes. Your plugin just shows the icons representing git status in NERDTree.

May I suggest you explain what the plugin exactly does (functionalities) in the README so as not to be confused with the others plugins in the gif.

Thanks for the quick reply & thanks for this awesome plugin.

**Comment by Xuyuanp** [comment]
Glad to hear that.

I do want to record a new gif for a long time. But... I'm too lazy. LOL
