### ISSUE TITLE
vim become very slow

### ISSUE THREAD

**Issue by SenZhangAI** [Xuyuanp/nerdtree-git-plugin#45]
I think it's very useful,
but when I use it, vim will become very slow,
I use `vim --startuptime` to test the startup time and found that the `BufEnter autocommands` time will become very large.

**Comment by Xuyuanp** [comment]
There is no `autocmd BufEnter` command in this plugin.

**Comment by SenZhangAI** [comment]
Thanks!
I think this may caused by my extreme environment，my test project modified lots of files and I use my vim in Cygwin and on my old computer.
