### ISSUE TITLE
Conflicted with syntastic in MacVim.

### ISSUE THREAD

**Issue by cissoid** [Xuyuanp/nerdtree-git-plugin#49]
After installed this plugin, syntastic no longer auto check after I executed `:w`, but manual call `:SyntasticCheck` still works fine.

I tested with the same .vimrc in terminal vim and this problem disappeared, so it only happen in MacVim.

Has there more details I should provide?

**Comment by Xuyuanp** [comment]
It works here.

Please make sure you are using the latest version of both plugins.
