### ISSUE TITLE
Git status markers still showing even though switched to a new, clean branch

### ISSUE THREAD

**Issue by JESii** [Xuyuanp/nerdtree-git-plugin#50]
I installed the plugin, made some changes to a branch, and the markers showed up perfectly - nice!

Howver, when I switched to a new branch, I still see the markers, Am I doing something wrong?

**Comment by Xuyuanp** [comment]
I don't actually know what's your problem. Could you please provide more details, such as screenshot and the output of `git status -s` command before and after you switched branch?

**Comment by JESii** [comment]
Will do; I'll have to reinstall and test it so it may take a bit...

**Comment by JESii** [comment]
OK; figured it out -- it was the 'dirty' indicators that caused the confusion, and now I see that there are untracked files in those 'dirty' branches. Thanks!

**Comment by Xuyuanp** [comment]
Glad to hear that. Happy Hacking!
