### ISSUE TITLE
git line status

### ISSUE THREAD

**Issue by keenwon** [Xuyuanp/nerdtree-git-plugin#55]
I don't have line status, need more plugins?

![image](https://cloud.githubusercontent.com/assets/5516478/17463647/036e237e-5cfd-11e6-90d3-f028479ab7b8.png)

**Comment by mike-zueff** [comment]
@keenwon, do you have https://github.com/airblade/vim-gitgutter installed?

**Comment by keenwon** [comment]
@mike-zueff after install vim-gitgutter, it works, thank you!
