### ISSUE TITLE
Prevents Syntastic from working when g:NERDTreeUpdateOnWrite isn't set to 0

### ISSUE THREAD

**Issue by sprt** [Xuyuanp/nerdtree-git-plugin#56]
My vimrc while debugging:

```
execute pathogen#infect()
call pathogen#helptags()
```

Repro: https://streamable.com/jlxk

After the first save, you can see the Syntastic window pop up as expected, but when I save again with NERDTree open, nothing happens. A workaround to this is to set `g:NERDTreeUpdateOnWrite` to 0 but it's obviously far from ideal.

Related to #6

**Comment by joserc87** [comment]
I have this issue as well. I found that nesting one of the autocmds in nerdtree-git-plugin (as suggested in https://github.com/vim-syntastic/syntastic/issues/1391#issuecomment-97310854) worked for me. So, I changed this line:
`autocmd BufWritePost * call s:FileUpdate(expand("%:p"))`
to:
`autocmd BufWritePost * nested call s:FileUpdate(expand("%:p"))`

That being said, I am not sure at all that this is the right solution. Maybe some of the developers of the plugin can tell me if that change makes sense, and if so, integrate it into nerdtree-git? And if it's not a good solution, what would be better?

Thank you

**Comment by RST-J** [comment]
I ran into the same issue but making the `autocmd BufWritePost` `nested` did not help in my case. Adding `let g:syntastic_nested_autocommands = 1` to my `.vimrc` did not change anything. Even if both commands were nested it didn't work (I have no idea of vimscript so I cannot judge that).

After experimenting a bit, I found out that the order in which the plugins are loaded affects the issue in my case. I moved `~/.vim/bundle/syntastic/` to  `~/.vim/bundle/a_syntastic/` and started a new vim session. With this change (and without having set the nested option for syntastic nor changing the command in nerdtree-git-plugin) both worked - syntastic checking on write and nerdtree-git-plugin updating on write.

**Comment by dmix75** [comment]
The real problem appears to be the nerdtree-git plugin.  Replace the function with the following:

function! s:FileUpdate(fname)
    if g:NERDTreeUpdateOnWrite != 1
        return
    endif

    if !g:NERDTree.IsOpen()
        return
    endif

    let l:winnr = winnr()
    let l:altwinnr = winnr('#')

    call g:NERDTree.CursorToTreeWin()
    let l:node = b:NERDTree.root.findNode(g:NERDTreePath.New(a:fname))
    if l:node != {}
        call l:node.refreshFlags()
        let l:node = l:node.parent
        while !empty(l:node)
            call l:node.refreshDirFlags()
            let l:node = l:node.parent
        endwhile
        call NERDTreeRender()
    endif

    exec l:altwinnr . 'wincmd w'
    exec l:winnr . 'wincmd w'
endfunction

Notice the if statment before had a return and when that happens the funcation never resets back to the original buffers.

**Comment by NickolasHKraus** [comment]
This [pull request](https://github.com/Xuyuanp/nerdtree-git-plugin/pull/131) provides a solution.

Thank you, @dmix75. This is the correct solution. However, it took some digging into the Syntastic and NERDTree source code to determine why.
