### ISSUE TITLE
No indicators

### ISSUE THREAD

**Issue by bgblanch** [Xuyuanp/nerdtree-git-plugin#57]
### Environment
OS: Ubuntu 16.04.1
Vim Version: 7.4

### Plugins
Vundle
NerdTree
NerdTree-Git-Plugin
Vim-Airline
Vim-Markdown
Syntastic

### .vimrc
[.vimrc gist](https://gist.github.com/bgblanch/4399327a3fd483fc3c1bad15682fbcbd)

### ISSUE
Unable to show indicators.  I have tried moving items in the .vimrc around as well as opening files in GVim, vi and vim.  I have also tried having NERDTree open when opening a file and not having it open.  In a nutshell, I'm not able to get it to work.  At this point, there isn't anything that I can think of to try differently.  There may be something simple that I'm not doing but I can't figure it out.

**Comment by bgblanch** [comment]
![image](https://cloud.githubusercontent.com/assets/9014841/17673539/333e039a-62e7-11e6-92ca-48a24c90bbce.png)

**Comment by Xuyuanp** [comment]
Is your pwd under a git repo? 
Is this repo clean?

**Comment by bgblanch** [comment]
I tried opening vim directly in the repo directory as well as doing a "C" within NERDTree to change the working directory with no luck.  I have also tried within "clean" and "dirty" repos (e.g. go into clean repo, alter some files, check to see if any indicators show, close vim, reopen vim to see if any indicators show).

**Comment by Xuyuanp** [comment]
What's the output of command `git status -s` under your work directory?

**Comment by bgblanch** [comment]
depends.  When in a "clean" repo, it returns nothing.  If I alter a file it shows a red "M" before the file on the command line but nothing shows in NERDTree.

**Comment by Xuyuanp** [comment]
I see, just delete this line `let g:loaded_nerdtree_git_status = 1`.  This is not a configurable var.

**Comment by bgblanch** [comment]
booyah!!!  I figured it was something stupid I did... Thank you!

**Comment by Xuyuanp** [comment]
Happy hacking!
