### ISSUE TITLE
Syntastic, mhinz/vim-signify not working 

### ISSUE THREAD

**Issue by delijati** [Xuyuanp/nerdtree-git-plugin#6]
Is seems that it overwrites the  chnages made from mhinz/vim-signify or syntastic.

**Comment by rtorralba** [comment]
I detected the same error, when i save the file with nerdtree opened nerdtree icon is updated but syntastic doesn't execute check process.

Seems that you catch on save event but doesn't broadcast it.

Thanks in advance for your work.

**Comment by drwX** [comment]
Syntastic 不能使用，应该是

**Comment by Xuyuanp** [comment]
@drwX 应该好了，是我忘记把焦点移回当前buffer

**Comment by delijati** [comment]
in english please

**Comment by Xuyuanp** [comment]
@delijati your issue has been fixed

**Comment by delijati** [comment]
@Xuyuanp ahh ok cool thanks :)

**Comment by jondkinney** [comment]
I'm having this issue currently. `:SyntasticInfo` says that it'll check my ruby file automatically with both `mri` and `rubocop` checkers:

![image](https://cloud.githubusercontent.com/assets/4521/7379849/608957c8-edbd-11e4-90cb-f8223d50a19d.png)

However, when I save the file it doesn't happen automatically. Seems these errors are returned:

![image](https://cloud.githubusercontent.com/assets/4521/7379860/7edb0014-edbd-11e4-9838-4b494ee442fc.png)

If I move the 'nerdtree-git-plugin' out of my bundle folder and the plugin isn't loaded, then saving the file does show the syntastic signs in the gutter successfully. Any thoughts on what regressed?

Thanks!

**Comment by Xuyuanp** [comment]
@jondkinney could you please show your vimrc about syntastic and my plguin?

**Comment by jondkinney** [comment]
My whole vim setup script is here: https://gist.github.com/jondkinney/2040114#file-vimrc_main

**Comment by jondkinney** [comment]
@Xuyuanp not sure if you saw this, but perhaps this is due to needing to nest autocmds - https://github.com/scrooloose/syntastic/issues/1391#issuecomment-97310854

Though, I tried adding the `nested` keyword where @lcd047 suggested and it didn't seem to fix the issue. It's possible I did it wrong though.

**Comment by lcd047** [comment]
@jondkinney As far as I can tell it solves _a_ problem.  But that may or may not be the problem you're seeing.

**Comment by Xuyuanp** [comment]
Sorry, everything is OK here.
No error occurs after saving file.

**Comment by jondkinney** [comment]
@Xuyuanp I'm revisiting this now and still having the same problem. I think you're not getting any errors on save because you don't have debug mode turned on for syntastic. I can 100% reproduce this problem and it only happens when `nerdtree-git-plugin` is part of my vim setup. Here's a little video showing the issue:

![repro](http://f.cl.ly/items/0u042a3X2r0X1M1y3w2l/repro.gif)

**Comment by jondkinney** [comment]
FYI, I did a little more troubleshooting and commenting out the aforementioned line  https://github.com/Xuyuanp/nerdtree-git-plugin/blob/55eb4f94a208ceff79e6526a906c44c3682daa44/nerdtree_plugin/git_status.vim#L239 does indeed fix syntastic. I'm not sure what that breaks though for nerdtree-git-plugin.

I tried adding that `nested` keyword as @lcd047 suggested  in https://github.com/scrooloose/syntastic/issues/1391#issuecomment-97310854 but it didn't seem to allow syntastic to work.

Any more thoughts on how to allow these plugins to work at the same time?

Thanks!!

**Comment by Xuyuanp** [comment]
@jondkinney Hi, I tried to debug this problem in a new clean env with `nerdtree`, `nerdtree-git-plugin` and `syntastic.vim` only. And I copied the config about these three plugins from yours, Then I did what you did in gif, everything is ok and works correctly as expected.

I also tried to use other filetypes (python with pylint and flake8, go with golint), it also worked.

**Comment by ethe** [comment]
Seems still have some problem, syntastic can not check on save(use :w).
好像还是不行啊，在用`:w`保存的时候syntastic依然无法进行语法检查。

**Comment by retrohacker** [comment]
@Xuyuanp I'm also experiencing this. When I have nerdtree auto-open at vimstart, syntastic doesn't auto-refresh.

**Comment by Alagon** [comment]
@Xuyuanp I'm also experiencing the same issue. And I find the reason you cannot reproduce is that another plugin CtrlP. If open a file searched by ctrlp, the error coming. If not, everything goes well.

**Comment by NickolasHKraus** [comment]
This [pull request](https://github.com/Xuyuanp/nerdtree-git-plugin/pull/131) provides a solution.
