### ISSUE TITLE
Not working for CentOS 6.7

### ISSUE THREAD

**Issue by JefferyXieTT** [Xuyuanp/nerdtree-git-plugin#65]
I am on CentOS 6.7. Installed vim7.4, nerdtree but this plugin doesn't work. 
1) do we support CentOS 6.7?
2) is there any log file available to see the plugin error? Or is there any command to view the plugin settings?

Thanks,
Jeffery

**Comment by jejer** [comment]
Same issue

**Comment by JefferyXieTT** [comment]
@jejer what did you mean?

**Comment by jejer** [comment]
@JefferyXieTT Git client in CentOS 6 doesn't support "git -c". So just edit nerdtree plugin source code to remove it.

**Comment by JefferyXieTT** [comment]
@jejer That works! You rock!
