### ISSUE TITLE
Can I configrate the position of symbols ?

### ISSUE THREAD

**Issue by honger05** [Xuyuanp/nerdtree-git-plugin#67]
the symbols ahead of filename/foldername makes me confuse the constructor.

I think at the end will be better.

**Comment by Xuyuanp** [comment]
Sorry, you can't. It's determined by nerdtree.

**Comment by honger05** [comment]
Sad!!

**Comment by sheharyarn** [comment]
@Xuyuanp Really hoping you'll change your mind about this, I would love if we could somehow show the symbols at the end of the file names instead.

Either way, love this plugin. Thanks for the awesome work!
