### ISSUE TITLE
处理 function vundle#config#bundle[2]..<SNR>4_check_bundle_name

### ISSUE THREAD

**Issue by Aiclear** [Xuyuanp/nerdtree-git-plugin#68]
I am using vim8.0 on windows 10, this plugin can work good on my vim, but when I open my gvim this statement "处理 function vundle#config#bundle[2]..<SNR>4_check_bundle_name" will happend everytime, I don't know why.

**Comment by Xuyuanp** [comment]
Are you sure it was caused by this plugin? Have you try to open vim disabling it.

**Comment by Aiclear** [comment]
yes，I did. But when I open my vim I meet it again.

**Comment by Xuyuanp** [comment]
Sorry, I can't debug this issue as I have no windows pc.
