### ISSUE TITLE
Doesn't work if vim's current working path is not under Nerdtree root path

### ISSUE THREAD

**Issue by filfirst** [Xuyuanp/nerdtree-git-plugin#70]
Hello,

After applying commit 18d52b5, this plugin doesn't work if vim's current working path is not under Nerdtree root path which is under a git repo.

Try running command "git -c color.status=false status -s /path/under/a/git/repo" outside the repo, git gives "fatal: Not a git repository (or any of the parent directories): .git"

**Comment by Xuyuanp** [comment]
Sorry, i don't know your mean. Could you provide some examples?

**Comment by filfirst** [comment]
Assume I have a repo /foo.
In terminal:
```sh
cd /foo
vim bar.cpp
```
The plugin works fine.
Then in vim:
```vim
:cd /home
```
Now current working path of vim is switched to /home, but b:NERDTree.root.path is still /foo.
So running "git status" by the plugin will result in "Not a git repository" error.

**Comment by KeithScheiwiller** [comment]
This actually affects more than that too. For example if my git repo is `/foo` but I start vim in `/foo/bar` then change NERDTree up to `/foo` the git status will no longer work.

This is because of the latest commit that removes the `cd`. If you start in a subdirectory then move elsewhere, NERDTree's working directory changes but NOT vim's. For example:

```
:echo system('pwd') . ' ' . b:NERDTree.root.path.str()
/home/src/classic-ux/src/controlpanel/ControlPanel                                                                                                                                                                                                                            
 /home/src/classic-ux/src 
```

Meaning the git status command outputs relative paths that don't make sense:
```
:echo system('git -c color.status=false status -s /home/src/classic-ux/src/')
 M ../../dashboards_v2/logging.cfg                                                                                                                                                                                                                                            
```

**Comment by KeithScheiwiller** [comment]
Actually, there is a win-win solution here. If you merge in https://github.com/Xuyuanp/nerdtree-git-plugin/pull/66/commits/7b2b554fbecd62fbc193543bffeb81d019c3cd53 it will take care of the issue with fish without causing regressions (just tested using bash & fish).

Problem with the old `system()` command is that fish doesn't allow `&&` preferring `command1; command2` instead. This isn't actually POSIX-compliant but using `;` instead will work in all shells.

**Comment by Xuyuanp** [comment]
Yes, @KeithScheiwiller is right.
