### ISSUE TITLE
git mv support

### ISSUE THREAD

**Issue by djmccormick** [Xuyuanp/nerdtree-git-plugin#71]
Feature request for NERDTree move to use `git mv` instead of reporting that the original file was deleted and a new one added.

**Comment by djmccormick** [comment]
Related: https://github.com/Xuyuanp/git-nerdtree/pull/8

**Comment by mguimas** [comment]
@Xuyuanp When do you expect to have this important feature? It is annoying to have to rename and move files outside of the editor.

**Comment by Xuyuanp** [comment]
It's not the responsibility of this plugin.
