### ISSUE TITLE
Truncated symbols

### ISSUE THREAD

**Issue by kuon** [Xuyuanp/nerdtree-git-plugin#73]
I have truncated symbols.

https://www.dropbox.com/s/xx3dp4tiza6h7tu/Screenshot%202017-02-02%2014.41.25.png?dl=0&raw=1

Do you know what might be causing this?

**Comment by Xuyuanp** [comment]
I'm not sure, I thought it was caused by your terminal

**Comment by kuon** [comment]
I'm using macvim. I guess it might cause the issue.
