### ISSUE TITLE
Syntastic + nerdtree-git-plugin: IOError: [Errno 2] No such file or directory: 'NERD_tree_1'

### ISSUE THREAD

**Issue by lafrech** [Xuyuanp/nerdtree-git-plugin#74]
I get this error when using nerdtree-git-plugin + syntastic:

```
NERDTree: Refreshing the root node. This could take a while... DONE
syntastic: error: checker output:
Traceback (most recent call last):
  File "/home/jerome/.vim/bundle/syntastic/syntax_checkers/python/compile.py", line 11, in <module>
    compile(open(argv[1]).read(), argv[1], 'exec', 0, 1)
IOError: [Errno 2] No such file or directory: 'NERD_tree_1'
syntastic: error: checker python/python returned abnormal status 1
```

If I remove nerdtree-git-plugin, it works fine.

Using latest versions of nerdtree and syntastic, git bisect tells me that the first bad commit in nerdtree-git-plugin is [`6564bb5`](https://github.com/Xuyuanp/nerdtree-git-plugin/commit/6564bb5f26fe123c3eead13d1b8a9d53d5f9f897) but this is because when I select an earlier commit I get other errors masking this one.

Using latest versions of nerdtree and nerdtree-git-plugin, git bisect tells me that the first bad commit in syntastic is [`adf899f`](https://github.com/vim-syntastic/syntastic/commit/adf899f1ba863b1ea2c3327e7cde79ba21354435).

I'm not sure which pluging is guilty, here. I emptied my `.vimrc` to rule it out.

**Comment by lafrech** [comment]
I asked on [Vi and Vim](http://vi.stackexchange.com/questions/11295/) and was told by Syntastic developer that this is known issue. He proposed a fix [here](https://github.com/vim-syntastic/syntastic/issues/1391#issuecomment-97310854).

**Comment by NickolasHKraus** [comment]
This [pull request](https://github.com/Xuyuanp/nerdtree-git-plugin/pull/131) provides a solution.
