### ISSUE TITLE
Non-starter

### ISSUE THREAD

**Issue by chrisbward** [Xuyuanp/nerdtree-git-plugin#75]
Installed the plugin, made a change on one of my files - saved it, GitGutter shows changes, NERDTree does not update.

I have the devicons installed - not sure if that will affect it?

This is the same for with/without tmux.

**Comment by fuelen** [comment]
the same for me

**Comment by Xuyuanp** [comment]
What's `devicons` mean? a plugin?

**Comment by chrisbward** [comment]
yes; http://vimawesome.com/plugin/vim-devicons

**Comment by Xuyuanp** [comment]
Ok, will try.

**Comment by ryanoasis** [comment]
> What's devicons mean? a plugin?

:cry: :relaxed: 

---

Hmm I also seem to be having issues :worried: 

I have disabled [VimDevIcons](https://github.com/ryanoasis/vim-devicons) but still have trouble seeing the flags. Confirmed plugin is loaded `:echo g:loaded_nerdtree_git_status` and enabled `:echo g:NERDTreeShowGitStatus`

---

FYI, best touchpoint for VimDevIcons is the GitHub Repo: https://github.com/ryanoasis/vim-devicons

**Comment by qifei9** [comment]
I had the same issue. I disabled all the other plugins and found that the git flags appear. Then I re-enabled all the other plugins, it still works. I do not understand why.

PS, the vim-devicons makes the brackets and color disappear, but the flag remain.

**Comment by fuelen** [comment]
I have the newest versions of all my packages and nerdtree-git-plugin isn't working correct.
My init.vim file has this line
```
cd ~/projects " set default working directory
```
when I remove this line, and navigate via nerdtree to directory with git - nothing happens, but when I started nvim in directory with git - it is ok. So, something with chdir

**Comment by blurm** [comment]
Exactly the same with @fuelen , have to start nvim in directory with git.

**Comment by fuelen** [comment]
@blurm you have to type 'cd' in selected directory

**Comment by blurm** [comment]
@fuelen dir changed, except that nothing happened

**Comment by fuelen** [comment]
@blurm and then press `R` (shift + r)

**Comment by christopher-lawrence** [comment]
I was having some issues with this plugin loading for me.  What @fuelen said worked for me.  Just to reiterate it... here is what seems to work for me:

Have the cursor over the root of the repo then run `cd` then refresh NerdTree `shift+r`

This will set the PWD to the root of the repo, which this plug-in needs.  Refreshing the root node seems get this plugin going.

I also found having autochdir seems to affect this plugin, so might want to make sure that is disabled.

**Comment by boostmerlin** [comment]
试了你们说的所有方法，还是不行·

**Comment by tterranigma** [comment]
I have this in my vimrc as a hacky, laggy fix:

```
autocmd BufEnter Nerd_tree_* NERDTreeRefreshRoot
```

**Comment by mhoonjeon** [comment]
I have this problem too, it used to work but after updating my neovim `shift+r` does not refresh and show changes.
