### ISSUE TITLE
Really slow since update a couple of days ago

### ISSUE THREAD

**Issue by bitboxer** [Xuyuanp/nerdtree-git-plugin#76]
A couple of days ago I updated the plugin and now my NerdTree is barely usable. I used the vim profiler and this function uses lots of time:

```
    8  39.638394  39.621555  NERDTreeGitStatusRefresh()
```

How can I help to debug this?

**Comment by Xuyuanp** [comment]
Wired. I did nothing before yesterday. Do you work under a directory with lots of files?

Please show me the output of  `git status -s --ignored`

**Comment by bitboxer** [comment]
Hm...could also be since yesterday? Not sure. The git command shows a nice output that I don't want to disclose here because I am working on a rather large private codebase for a company right now. The `time` command says this:

```
git status -s --ignored  0.32s user 1.40s system 26% cpu 6.408 total
```

This is part of the output without paths:

![screen shot 2017-02-21 at 10 55 10](https://cloud.githubusercontent.com/assets/56195/23159741/418415c0-f824-11e6-8f76-6a88364a34f6.png)

**Comment by Xuyuanp** [comment]
This seems to be result of showing tons of ignored files. You can checkout the previous version temporary. I will add a configurable var to turn on/off this feature later.

**Comment by bitboxer** [comment]
Awesome. Thank you!

**Comment by ismay** [comment]
Can confirm that I'm experiencing this as well. I think in my case because I have an ignored node_modules folder (which is huge).

**Comment by Xuyuanp** [comment]
I just added a switch var `g:NERDTreeShowIgnoredStatus`(0 default). 

See more details in 76cd21b1259d2242edce3d62247d0b7b5c77e33e

**Comment by bitboxer** [comment]
Awesome. Thanks!

**Comment by ismay** [comment]
Any details on how we can update the performance of using `IgnoredStatus`? I'd really like to have something like that in nerdtree, would make it much more obvious if a file is ignored or not (which is currently not visible at all).

I suspect that the performance penalty in my case was due to the `node_modules` folder, which it probably tried to parse completely (instead of stopping at the top-level folder, which is already ignored). Could this be solved by optimising the parsing/setting of an ignored status?

@poberherr, @runoshun

**Comment by unphased** [comment]
This doesn't seem to work for me. Indeed the use of `--ignored` leads to the `git status` call taking over 10 seconds to complete, it's a dealbreaker for sure in this particular repo I have here. 

What's concerning is that this blockage leads to extreme sluggishness in the other buffers in vim, but it is not true blockage, as it still responds to my movement commands within one second. 

So, something is wonky here. 

I did confirm that the performance penalty is lifted when I remove nerdtree-git-plugin from vim, so it is SOMETHING in this repository that causes massive slowdown when in a large repository tree. For the time being I'm looking into alternatives to NERDtree.

**Comment by tiberiuichim** [comment]
It slowed down neovim for me, too, so I've just removed this plugin, fixes my problem. Too bad.

**Comment by chenpengcheng** [comment]
Installed it this week. `vim` has become very slow during editing. Did profiling and found this:

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
 1700  85.322661  42.386813  159()
   21  31.089606   0.001941  <SNR>49_CursorHoldUpdate()
 3005  29.198246   0.047503  37()
 3005  27.180360   1.148078  3()
99243  26.001736   1.072590  31()
205374  25.802976  10.675909  39()
204660  14.423497   7.101849  44()
 1301  12.402823   0.019071  127()
207665   6.067426   4.679387  33()
 2961   3.693131   3.495866  130()
415333   2.749236             nerdtree#runningWindows()
 3005   1.970383   0.145710  262()
   21   1.940812   0.000404  NERDTreeRender()
   21   1.940408   0.000186  nerdtree#renderView()
   21   1.940222   0.000399  230()
   21   1.939823   0.006460  251()
 3005   1.733434   0.114326  NERDTreeGitStatusRefreshListener()
 3005   1.604585   0.387397  NERDTreeGetGitStatusPrefix()
   21   1.364450   0.000459  129()
   24   1.304699   0.009981  <SNR>139_AutoUpdate()
```

Without this plugin and doing same operations:
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   57   7.075442   0.029403  <SNR>138_AutoUpdate()
    5   5.359748   0.002134  <SNR>61_UpdateErrors()
    5   5.344581   0.003847  <SNR>61_CacheErrors()
    6   5.303772   0.003203  syntastic#util#system()
    5   5.016568   0.000211  280()
    5   5.015975   0.001244  279()
    5   5.012961   0.000706  SyntaxCheckers_javascript_eslint_GetLocList()
```

Look like we are invoking some methods on the order of 200K when editing just 2 lines of a file.

**Comment by TaDaa** [comment]
noticed this as well.  My issue seems to occur when the autocmd CursorHold event / s:CursorHoldUpdate fires.  Any pauses in the cursor that hit updatetime block the UI which can be pretty bad depending on the directory size -- could just boil down to how slow NERDTree is at refreshing on large directories -- will have to dig into it more later
