### ISSUE TITLE
Fuzzy finder for git command

### ISSUE THREAD

**Issue by yahyalexandre** [Xuyuanp/nerdtree-git-plugin#83]
HI!

Don't know if it's a real issue of the plugin : I don't know how to access to the fuzzyfinder to fugitive command poping at the top (something you show in that gif ; https://camo.githubusercontent.com/3fe0388df11cb787f36e1fa108398fd3f757eef4/687474703a2f2f692e696d6775722e636f6d2f6a534377476a552e6769663f31)

I don't see any mention of it in the documentation... Is this a part of the plugin or a third party ?

Thanks

**Comment by Xuyuanp** [comment]
It's not. See more [unite.vim](https://github.com/Shougo/unite.vim.git)
