### ISSUE TITLE
Statuses don't update when changed with fugitive.vim

### ISSUE THREAD

**Issue by joeddav** [Xuyuanp/nerdtree-git-plugin#84]
It'd be great if the status symbols would change when staging, etc., using fugitive.vim. As is vim has to be reopened.

**Comment by Xuyuanp** [comment]
This is because that nerdtree can't handle that event. Switch to nerdtree
window and press `R` to force refresh.

**Comment by joeddav** [comment]
Great - that'll work. Thanks.

**Comment by jeffvandyke** [comment]
I know this is closed, but for folks winding up at this issue who don't want to have to worry about manually refreshing NERDTree whenever the index or the work tree changes from vim-fugitive, is there a .vimrc way to automate that?

**Comment by eduardofischer** [comment]
That issue should not have been closed. It would be very nice to have NERDTree updating itself when using fugitive...

**Comment by Xuyuanp** [comment]
@eduardofischer, please take a look.
