### ISSUE TITLE
How to display the changed line symbols before the line number?

### ISSUE THREAD

**Issue by Weiming-Hu** [Xuyuanp/nerdtree-git-plugin#85]
Thank you for your awesome plugin.

A small question. I saw in your GIF demo that your VIM shows the changed line symbol '+' before the line number. Do I need extra configuration to turn on this feature?

I'm also using YouCompleteMe plugin, which will show some symbols before the line number where the line has possible errors. Is it going to be a potential conflict?

Thank you.

**Comment by Xuyuanp** [comment]
[gitgutter](https://github.com/airblade/vim-gitgutter)

**Comment by Weiming-Hu** [comment]
Thank you.
