### ISSUE TITLE
Slow on large repo

### ISSUE THREAD

**Issue by trungdq88** [Xuyuanp/nerdtree-git-plugin#86]
Is this a bug or is it just how it works?
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
...
   24   0.598975   0.000433  NERDTreeGitStatusRefreshListener()
    2   0.593274   0.593085  NERDTreeGitStatusRefresh()
   24   0.279575   0.001217  NERDTreeGetGitStatusPrefix()
   23   0.035159   0.002460  airline#check_mode()
...
```

`NERDTreeGitStatusRefresh` took `0.593085` secs.

My repo has about `1401` files:
```
git ls-files | wc -l
1401
```

Total files in the repo directory (include ignored files):

```
find ./ -type f | wc -l
   82266
```

**Comment by andresbrocco** [comment]
I am having the same issue! My repo has 28k items, and with the plugin enabled, my vim takes about a second to move the cursor!

**Comment by Xuyuanp** [comment]
@andresbrocco this plugin doesn't handle `CursorMoved` event
