### ISSUE TITLE
Nvim crashes(?) with plugin installed

### ISSUE THREAD

**Issue by draganczukp** [Xuyuanp/nerdtree-git-plugin#87]
When opening a file it seems like the current buffer gets overwritten with a broken NERDtree after a few seconds. [This is how it looks like.](https://i.imgur.com/UJ79Mwi.png)
I know it's this plugin, because it stops doing that as soon as I remove it. I tried with multiple files, some were in git, some were not, some were a symlink to a git repo and they all had this issue.

Output of :mes
`Wykryto błąd podczas przetwarzania function <SNR>111_SetupListeners:
wiersz    1:
E121: Undefined variable: g:NERDTreePathNotifier
Wykryto błąd podczas przetwarzania function <SNR>111_SetupListeners:
wiersz    2:
E121: Undefined variable: g:NERDTreePathNotifier
Wykryto błąd podczas przetwarzania function <SNR>111_SetupListeners:
wiersz    3:
E121: Undefined variable: g:NERDTreePathNotifier
`
My current nvim is [here](https://gist.github.com/4d8832828cae46bc1fd114dbb5325c9d)

Both NERDtree and this plugin are up to date (updated with :PlugUpdate)

**Comment by Xuyuanp** [comment]
Sorry for too late. Does it work now?
