### ISSUE TITLE
how to remove []?

### ISSUE THREAD

**Issue by Val-istar-Guo** [Xuyuanp/nerdtree-git-plugin#88]
.vimrc file: https://gist.github.com/Val-istar-Guo/6f894a13878cf0c2cec6099b8e777c80

![image](https://user-images.githubusercontent.com/12405937/28007053-8395af82-6584-11e7-9f56-cf387ebac0b0.png)

**Comment by ryanoasis** [comment]
try
```vim
:set conceallevel=3
```

**Comment by Val-istar-Guo** [comment]
thanks
