### ISSUE TITLE
Am I supposed to be seeing the lines marked for staging in the vim gutter? Or do I have to install 'vim gitgutter' separately?

### ISSUE THREAD

**Issue by joaqo** [Xuyuanp/nerdtree-git-plugin#89]
Just asking because in the example [gif](https://camo.githubusercontent.com/3fe0388df11cb787f36e1fa108398fd3f757eef4/687474703a2f2f692e696d6775722e636f6d2f6a534377476a552e6769663f31) the lines are marked with a green `+` sign. I am not seeing them currently after installing this plugin. Everything else is working perfectly though, so thanks for the great plug in!

**Comment by sparky005** [comment]
Yes, that will require vim-gitgutter. @joaqo
