### ISSUE TITLE
Unable to use `fugitive :Gwrite`, errors detected when `NERDTree` is on

### ISSUE THREAD

**Issue by sitilge** [Xuyuanp/nerdtree-git-plugin#90]
Environment:

    Operating System: 4.12.8-2 generic arch linux

    Vim version NVIM v0.2.0

    NERDTree version 5782b22

    NERDTree settings (letting NERDTreeTabs manage the NERDTree):

    " Start NERDTreeTabs on GUI if dir selected
    let g:nerdtree_tabs_open_on_console_startup=2
    let g:nerdtree_tabs_smart_startup_focus=2
    let g:nerdtree_tabs_focus_on_files=1

    " Show hidden files
    let NERDTreeShowHidden=1

Process:

    Open a file
    Run Glog from fugitive plugin
    Run cnext
    Run Gwrite

Current Result:

![image](https://user-images.githubusercontent.com/3306642/29840794-dea2a9d0-8d0b-11e7-9b93-f7d799e4ae1a.png)

Message:

The previous issue was opened [here](https://github.com/scrooloose/nerdtree/issues/736#issuecomment-325720036), however, the bug seems to be `nerdtree-git` related because the matching script from `:scriptnames` points to `<SNR>46_` which belongs to `nerdtree-git-plugin/nerdtree_plugin/git_status.vim`.

**Comment by OliverLew** [comment]
Same error here. I use the Gvdiff to stage hunks in a file, and some similar errors come up when I try to save the file.
After I disabled the plugin, the error is gone.

**Comment by joelhellman** [comment]
I get this as well if I execute `:Gwrite` on a buffer opened with `:Gdiff` while NERDTree is open. If I toggle/close NERDTree first, `:Gwrite` works - so that's my workaround for now.

OS: CentOS release 6.7
Vim: 8.0 and 7.4

My .vimrc has these plugins
```
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'xuyuanp/nerdtree-git-plugin'
Plug 'tpope/vim-fugitive'
```

Here is the error in plain text
```
Error detected while processing function <SNR>41_FileUpdate..32..35:                                                                  
line   18:                                                                                                                            
E605: Exception not caught: NERDTree.InvalidArgumentsError: Invalid path = /home/vagrant/fugitive:///home/vagrant/.git//0/.bashrc     
Error detected while processing function <SNR>11_Write:                                                                               
line   50:                                                                                                                            
E171: Missing :endif                                                                                                                  
```

**Comment by lyhappy** [comment]
I had the same error, and have a glance at the source code.
![image](https://user-images.githubusercontent.com/15372879/48398890-13810f00-e75d-11e8-9215-5cf5bd0d73ef.png)
The problem is probably caused by line 305.
I add an if statement before line 293 to avoid the error msg. Not a good solution, but useful.

```vimrc
function! s:FileUpdate(fname)
    if a:fname =~# '^fugitive'
        echomsg a:fname
        return
    endif
    " ...
endfunction
```

**Comment by huangzonghao** [comment]
Great solution above. Hope it could be included as a patch.

**Comment by Xuyuanp** [comment]
Sorry for too late. I try to reproduce the error step by step, but got a different error message `E502 "<my work dir>" is a directory`
