### ISSUE TITLE
Syntax highlighting lost when used more than one character

### ISSUE THREAD

**Issue by kristijanhusak** [Xuyuanp/nerdtree-git-plugin#92]
Syntax highlighting is lost when using more than one character for a custom indicator:

Before:
![Before](https://i.imgur.com/PlIp9yf.png)

After using these indicators (Added `a` to dirty):
```vimL
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "✹",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗a",
    \ "Clean"     : "✔︎",
    \ 'Ignored'   : "☒",
    \ "Unknown"   : "?"
    \ }
```
![After](https://i.imgur.com/IZReXzt.png)

I used `a` above, but i wanted to inject an empty space initially. It messes up anyway.

I tried updating the part with `syn match` to fix it, but i'm not really familiar how that exactly works.

**Comment by repromancer** [comment]
Came across the same problem yesterday. I'm using size 9 font, which doesn't grant me the greatest special character support, so I wanted to set everything to two-letter abbreviations for better readability.

My complete lack of vimscript experience did not come in handy here (:cry:), but for now I decided on a more readable set of special characters:

```
let g:NERDTreeIndicatorMapCustom = { 
    \ "Modified"  : "↪",
    \ "Staged"    : "↗",
    \ "Untracked" : "+",
    \ "Renamed"   : "↻",
    \ "Unmerged"  : "⇆",
    \ "Deleted"   : "−",
    \ "Dirty"     : "!",
    \ "Clean"     : "·",
    \ 'Ignored'   : 'x',
    \ "Unknown"   : "?" 
    \ }
```
