### ISSUE TITLE
nerdtree-git-plugin does not work in repositories residing in a path with special characters

### ISSUE THREAD

**Issue by martinhj** [Xuyuanp/nerdtree-git-plugin#93]
I noticed that nerdtree-git-plugin do not work in repositories under paths with special characters (in my case white spaces).

I'm using nvim v0.2.0 and zsh.

**Comment by pmuens** [comment]
I think I'm facing the same issue. I have my files in iCloud Drive which has a weird path.

Here's the error I get:

```
"." is a directory
Error detected while processing function nerdtree#checkForBrowse[9]..185[2]..186[17]..187[8]..151[25]..149[15]..261[4]..NERDTreeGitStatusRefreshListener[5]..NERDTreeGetGitStatusPrefix:
line   11:
E33: No previous substitute regular expression
Error detected while processing function nerdtree#checkForBrowse[9]..185[2]..186[17]..187[8]..151:
line   25:
E171: Missing :endif
```

**Comment by hernang87** [comment]
Same here, using macOS 10.13.4, vim 8.0.1283

**Comment by zapashcanon** [comment]
#80 and #94 probably fixed this so this can be closed, @martinhj can you confirm ?
