### ISSUE TITLE
incorrect highlight for custom indicator

### ISSUE THREAD

**Issue by pirey** [Xuyuanp/nerdtree-git-plugin#96]
I use these custom indicator
```
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "M",
    \ "Staged"    : "S",
    \ "Untracked" : "+",
    \ "Renamed"   : "R",
    \ "Unmerged"  : "!",
    \ "Deleted"   : "D",
    \ "Dirty"     : "!",
    \ "Clean"     : "C",
    \ 'Ignored'   : '☒',
    \ "Unknown"   : "?"
    \ }
```
because I use regular character, I think the plugin incorrectly detect any folder name starting with one of those custom indicators.

Here, the char `C` and `M` in folder `Console` and `Modules` are highlighted, which is not supposed to.

![image](https://user-images.githubusercontent.com/10344542/32693740-67159aa8-c762-11e7-9ba5-23e3331ca1fc.png)

The indicator, however works fine when I try to edit or add new file, see the file `Handler.php`

**Comment by pirey** [comment]
I'm using vim 8 in linux inside tmux session.

**Comment by danielmoraes** [comment]
up

**Comment by tlhunter** [comment]
This is still broken. I _think_ the symbols are used in a regex, and the author only anticipated unicode characters, and using normal ascii is causing issues.

**Comment by pirey** [comment]
I have created pull request to fix this issue, does anyone knows who can help to merge it?

**Comment by tlhunter** [comment]
It looks like @Xuyuanp has performed the last three merges.

**Comment by soupss** [comment]
A temporary workaround could be to replace the indicators with letterlike symbols. That still looks better than the default indicators imo.

**Comment by soupss** [comment]
Works great :)
![image](https://user-images.githubusercontent.com/12647468/77210441-4c738580-6b01-11ea-92f5-db6d17045446.png)

Made with https://lingojam.com/TextSymbols%28Letters%29 lol

**Comment by Xuyuanp** [comment]
see #119
