### ISSUE TITLE
Cant get the symbols to render

### ISSUE THREAD

**Issue by luis-alves** [Xuyuanp/nerdtree-git-plugin#97]
**Environment**
OS: Bash on Ubuntu on Windows
Vim Version: 7.4

**Plugins**
Gundo
NerdTree
Nerdtree-git-plugin
syntastic
vim-airline
vim-colors-solarized
vim-devicons
vim-distinguished
vim-javascript
vim-material-monokai
vim-monokai
vim-nerdtree-syntax-highlight
vim-sensible

**Nerdfont**
LiterationMono NF

**ISSUE**

When I copy the vimscript: 
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "✹",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ 'Ignored'   : '☒',
    \ "Unknown"   : "?"
    \ }
 to .vimrc it does not display the symbols between the quotes, and in the nerdtree it only appears a square in some cases.

**Comment by Andrioshe** [comment]
same problem.. any fix?

**Comment by Xuyuanp** [comment]
Sorry, too late
Does it work now?
